### ISSUE TITLE
IsExperienceEditor

### ISSUE THREAD

**Issue by huzzi** [Sitecore/Habitat#107]
I'm getting this error message below with the latest pull.

`'Context.PageMode' does not contain a definition for 'IsExperienceEditor'	Sitecore.Feature.Navigation	C:\Projects\Habitat\src\feature\Navigation\code\Controllers\NavigationController.cs	56`

**Comment by dashkodo** [comment]
Please use Sitecore.Kernel 8.1

**Comment by huzzi** [comment]
Thanks, I had 8.1 installed but upgrading to 8.1 Update-1 seem to have fixed it.
