### ISSUE TITLE
Suggestion- Exception Handling, Mode (Preview & Editor), ORM (Glass Mapper)

### ISSUE THREAD

**Issue by c-prakash** [Sitecore/Habitat#110]
Hi, Here are few suggestions I have which will make this solution more independent from content. 

1. Exception Handling - I wrote an article to support multi-site exception handling
[http://cprakash.com/2014/12/29/exception-handling-in-sitecore-mvc/](http://cprakash.com/2014/12/29/exception-handling-in-sitecore-mvc/)

2. Content Mapping - I have used model binder implementation along with Glass Mapper previously to abstract the mapping logic out of controller and have the content available when controller start execution. It will remove lot of static references from code, make controller responsible only for business data and unit testable. 

[https://github.com/c-prakash/SitecoreExtensions/tree/master/Framework/Bootstrap/GlassMapper](https://github.com/c-prakash/SitecoreExtensions/blob/master/Framework/Bootstrap/GlassMapper/GlassAttribute.cs)

3. Preview & Editor Mode - Most of the time, we don't need controller code to be called in Preview & Editor mode, a filter can be added which can inspect the PageMode and return the model along with content by using the model binder.

**Comment by Eldblom** [comment]
Thanks for the suggestions. There are currently no plans to implement an ORM like glass mapper in the Habitat solution. Firstly it adds another dependency, which means increased maintenance considerations. Secondly it adds a learning curve and complexity to the solution which is not good for a standard Sitecore example. In a customer production solution it should naturally be seriously considered.
The exception handling post is really good and the considerations has been added to our backlog for http error handling
