### ISSUE TITLE
Missing one template in inheritance chain of NewsList Template item

### ISSUE THREAD

**Issue by harshbaid** [Sitecore/Habitat#119]
Hi @Eldblom,

From Sitecore Content Editor shows this template as 'Item Not Found' {A28A44A6-0DF1-49BF-83AD-CD21ABB9AF7E} when checking inheritance chain on NewsList template ( {A99866E5-08E7-44D8-8A52-F8E26BCD3714} )

Reference: https://github.com/Sitecore/Habitat/search?utf8=%E2%9C%93&q=A28A44A6-0DF1-49BF-83AD-CD21ABB9AF7E

![image](https://cloud.githubusercontent.com/assets/5327002/13583945/12ed54dc-e4da-11e5-9f53-c0a264d7b7f6.png)

**Comment by stasmaxymov** [comment]
It is an old reference to _HasSummary template, which is not exist and replaced with _HasPageContent.
