### ISSUE TITLE
is xdb a requirement?

### ISSUE THREAD

**Issue by donavonyoung** [Sitecore/Habitat#128]
So is xdb required? There is no mention of it in the install notes.

Did an install with the new process and it appears everything went smoothly. 

When i run habitat.local from the browser it appears to be tripping up on the xdb calls. Everything works fine in the content/xp editor/preview.

Here is the error we get back:

> Value cannot be null.
> Parameter name: source
> 
> return this.outcomeManager.GetForEntity<IOutcome>(new ID(Tracker.Current.Contact.ContactId));
> Source File: C:\Projects\Habitat\src\Feature\Demo\code\Models\Repository\OutcomeRepository.cs    Line: 68 

I saw there were some commits around this code yesterday. Not sure if that has anything to do with it.

**Comment by Eldblom** [comment]
Thanks for the heads up. We have not tested Habitat in Experience Management mode, i.e. with tracking disabled - but I cannot see that it should be a problem.
The error you are seeing seems to be a big related to the behaviour panel and the latest outcome commit. We will got on it ASAP.

**Comment by donavonyoung** [comment]
ok. so we installed mongo through sim and everything is working fine. We are working off a fresh vm instance to allow us to allow us to document the installation process and any issues that may arise. The only other issue we came across was a permissions issue with powershell when executing the `"05-Sync-Unicorn"` task. This was solved by executing `Set-ExecutionPolicy -ExecutionPolicy unrestricted -Force` in both 32 and 64 bit versions of powershell(ran as administrator).

**Comment by Eldblom** [comment]
Thanks for the testing, we will update the PowerShell scripts accordingly.
If you want to run Sitecore without xDB, it's not quite as simple as disabling MongoDB. Please follow the steps for enabling Experience Management mode. https://doc.sitecore.net/sitecore_experience_platform/setting_up__maintaining/experience_management/experience_management_an_overview
We have done some early testing on Habitat in this mode which revealed some minor problems. We will put a more rigorous test effort into our backlog.

Best Regards,
Thomas Eldblom
