### ISSUE TITLE
Final layout contents being deleted

### ISSUE THREAD

**Issue by kamsar** [Sitecore/Habitat#136]
To reproduce this, which I'm assuming is related to some kind of layout stuff in Habitat:

* Create a new `Article` page under `/sitecore/content/Habitat/Home/Modules/Feature`
* Enter experience editor.
* Add any rendering to `Narrow Section`, say `Inner 1 Column`
* Save the page
* Delete the added rendering, leaving `Narrow Section` empty
* Save again

Result: "Layout not found" error. It looks like something is zeroing out the final renderings instead of resetting them to the standard shared layout.

This is on Habitat https://github.com/Sitecore/Habitat/commit/12b50bd94927e12d8802aac2284ec6df60ba31ef using Sitecore 8.1 Update-2.

As a workaround you can reset the `__Final layout` to standard values to get your renderings back.

**Comment by Krusen** [comment]
Aha, so we are not the only ones experiencing this. 

We have this on a completely separate solution, where I think the only thing that is directly reused from Habitat is the same dynamic placeholders package. I have a feeling this might be the culprit.

**Comment by Eldblom** [comment]
After some digging around, I found out that this is actually an issue in Sitecore itself.  
When the standard values of an item has a partial layout in the Final Renderings field, the Experience Editor will save a empty string in the Final Rendering field - which leads to the whole layout being blank.   
You can test this yourselves by spinning up a clean Sitecore (8.1u2) and add the following xml `<r xmlns:p="p" xmlns:s="s" p:p="1"></r>` to the Final Renderings field in the standard values of the Sample Item template and subsequently edit Home item in the Experience Editor.  
The issue has been reported to Sitecore Support.

**Comment by Eldblom** [comment]
Hmm, well it's not exclusively related to the issue above, but it seems to be a general issue with Sitecore. Working with Sitecore Support on the issue.

**Comment by nsgocev** [comment]
I noticed this on another project when upgrading from 8.1u1 to 8.1u2. You
can also just place a blank space inside the FinalRenderings field and it
will break everything down the chain.

2016-04-22 6:15 GMT+03:00 Thomas Eldblom <notifications@github.com>:

> Hmm, well it's not exclusively related to the issue above, but it seems to
> be a general issue with Sitecore. Working with Sitecore Support on the
> issue.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Sitecore/Habitat/issues/136#issuecomment-213226435>
>



-- 
Nikola Gotsev

Please consider the environment before printing this email.

**Comment by Eldblom** [comment]
In some (fairly obscure) cases I'm guessing it could make sense to be able to clear the layout completely on a page by setting the Final Renderings to an empty value. In this case there is a clear difference between an empty string value and a not set field.
So I would say that the bug is in the Experience Editor, not the way Sitecore resolves the layout deltas.

**Comment by jbrownsp** [comment]
@Eldblom Do you have a public reference number for the FinalRenderings bug or have you been given a hotfix?

**Comment by Eldblom** [comment]
Yes, just got the hotfix yesterday, although haven't tested it yet. The public reference number is 108023.

https://kb.sitecore.net/articles/853187

**Comment by RyanTuckNZ** [comment]
How has this patch worked out for you guys? We have a fairly major issue where a template in our UAT environment has inadvertently had Presentation in the __Final Renderings field, and clients have been creating many pages using this Template. Now if I remove the _Final Renderings field value from the Standard Values it will destroy all Presentation on the items using this template. Urrrgh

**Comment by jbrownsp** [comment]
@RyanTuckNZ I actually haven't tried it yet. I had put a workaround in the save pipeline to reset the renderings fields if they were blank. It's not ideal but it's working until we have time to test out the hotfix.

You can download the hotfix Sitecore provided me here: http://54.86.191.98/Sitecore108023-RenderingsHotfix.zip

**Comment by hanwesh** [comment]
I think I have the same issue in general. I raised a sitecore support 465000

**Comment by Eldblom** [comment]
As previously mentioned, this issue is in no way associated with Habitat but Sitecore XP generally. We will integrate the hotfix into our build but will not distribute it here in the github repo. Please contact Sitecore support at reference hotfix 108023 and they will provide you with the package.
