### ISSUE TITLE
Do not Forget to Start your MongoDB

### ISSUE THREAD

**Issue by FrankFEspitia** [Sitecore/Habitat#147]
Once I finished the execution of all steps, even the unicorn synchronization I was facing an error in OutcomeRepository class (null value exception), this was because I did not have Mongo server running, 
This is to remind you to start MongoDB or just disable it in case you do not want to use it before launch habitat website.

Rgds

**Comment by Eldblom** [comment]
Thanks for the update - we will update the documentation.

We are testing for running Habitat without xDB, i.e. in Experience Management mode - [please note that this includes more than not having a running MongoDb.](https://doc.sitecore.net/sitecore_experience_platform/setting_up__maintaining/experience_management/experience_management_an_overview)
