### ISSUE TITLE
Sitecore List Manager is not working due to route conflict.

### ISSUE THREAD

**Issue by anthonyhook** [Sitecore/Habitat#151]
![image](https://cloud.githubusercontent.com/assets/1655469/14629988/caee9e1c-064d-11e6-9921-eb59146ae016.png)

**Comment by anthonyhook** [comment]
List Manager upload hangs when running with Habitat latest version.

**Comment by sergeyshushlyapin** [comment]
@anthonyhook the conflict is rather with the Speak Media Controller (which is used in List Manager):
```
Name: Sitecore.Controllers.MediaController 
Assembly: Sitecore.Speak.Client 
```
