### ISSUE TITLE
CI-Do-Magic gulp task

### ISSUE THREAD

**Issue by DavidBR-SW** [Sitecore/Habitat#152]
Are any docs surrounding the gulp CI tasks and how to use them? Specifically, what is the intended usage of package.xml output?

**Comment by dashkodo** [comment]
Hi David, CI_Do_magic task just only call subset of other tasks required to prepare environment to build package of Habitat,
actually it is used to build correct package.xml file.

**Comment by DavidBR-SW** [comment]
Thanks for your answer, dashkodo. How is the package.xml file ultimately used? I can't see any other references to it within the solution.

**Comment by dashkodo** [comment]
It is used in CI to generate package, we are using internal tools to generate sitecore package which is calling package designer code inside, but actually you can push generated package.xml to your installed habitat and create package using default package designer.

**Comment by DavidBR-SW** [comment]
Thanks for all your help!
