### ISSUE TITLE
Task runner has no task

### ISSUE THREAD

**Issue by GoranHalvarsson** [Sitecore/Habitat#16]
Task runner explorer cant find tasks. I had to comment out following lines in order to get the task runner to find and run the tasks.

//var msbuild = require("gulp-msbuild");
// var debug = require("gulp-debug");
// var foreach = require("gulp-foreach");
// var watch = require("gulp-watch");
// var newer = require("gulp-newer");
// var util = require("gulp-util");
// var runSequence = require('run-sequence'); 

Got it to work after doing a "Install gulp-install as a development dependency"
npm install --save-dev gulp-install

Which updated the package.json file:
"devDependencies": {
    "gulp": "^3.9.0"
  }

**Comment by Eldblom** [comment]
Thanks for the input. You have to open a command line and run "npm install" in the root of the project. This will install all the correct node modules. Also make sure you are running the latest version of node.
https://nodejs.org/en/

**Comment by GoranHalvarsson** [comment]
Thank you :-)
