### ISSUE TITLE
running gulp task '05-Sync-Unicorn'

### ISSUE THREAD

**Issue by istern** [Sitecore/Habitat#166]
throws the following error
Error: Command failed: C:\WINDOWS\sa
ystem32\cmd.exe /s /c "powershell -executionpolicy unrestricted "./Sync.ps1 -secret kl3KGocnbp3L9ncCZYRPwFwiW7jW2UhE02T3GZU6sL5rTCKZzsRyRYLtGzuh8Li -url http://sitecoreapp.local/unicorn.aspx""
./Sync.ps1 : The term './Sync.ps1' is not recognized as the name of a cmdlet, function, script file, or operab le program. Check the spelling of the name, or if a path was included, verify that the path is correct and try  again.
At line:1 char:1
+ ./Sync.ps1 -secret kl3KGocnbp3L9ncCZYRPwFwiW7jW2UhE02T3GZU6sL5rTCKZzs ...
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./Sync.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
oted
It seems to be related to cwd not being used

quick fix in pull request
https://github.com/Sitecore/Habitat/pull/167

**Comment by saddamgour** [comment]
actually same issue i have faced please tell me how can we fix it?
