### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by GoranHalvarsson** [Sitecore/Habitat#17]
I did a pull today and ran the task runner. Now when trying to browse to the page I get error:
Required license is missing: Runtime

The license is in place in the data folder, the LicenseFile settings looks alright and finally the patch DataFolder.config has the correct path to the data folder.

This is so strange...
Any ideas?

**Comment by steviemcg** [comment]
Looked at DevSettings.config?

On 13 Nov 2015, at 19:41, G?ran Halvarsson <notifications@github.com<mailto:notifications@github.com>> wrote:


I did a pull today and ran the task runner. Now when trying to browse to the page I get error:
Required license is missing: Runtime

The license is in place in the data folder, the LicenseFile settings looks alright and finally the patch DataFolder.config has the correct path to the data folder.

This is so strange...
Any ideas?

-

**Comment by GoranHalvarsson** [comment]
Yes and it points to the project, Like this  
<sc.variable name="sourceFolder" value="D:\Projects\Habitat\Habitat\src" />

**Comment by GoranHalvarsson** [comment]
Ah it seems to have expired, I used the "MVP" license. :-(
Ok so you guys can just close this :-)
