### ISSUE TITLE
Wrong value on the "Copy Local" attribute of the Sitecore.Kernel reference

### ISSUE THREAD

**Issue by lautarobonetto** [Sitecore/Habitat#173]
I'm seeing several error messages on the publish action in many projects.
In all the cases GULP cannot copy the Sitecore.Kernel.dll file, because it's being by another process.
If you change the "Copy Local" attribute on the reference of that assembly To FALSE, I think the issue will be solved.

Thanks
Lautaro

Error details:
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Deploy\Microsoft.Web.Publishing.Deploy.FileSystem.targets(96,5): error : Copying file obj\Debug\Package\PackageTmp\bin\Sitecore.Kernel.dll to C:\in
etpub\wwwroot\Test1\Website\bin\Sitecore.Kernel.dll failed. The process cannot access the file 'C:\inetpub\wwwroot\Test1\Website\bin\Sitecore.Kernel.dll' because it is being used by another process. [C:\XXXX\Habitat-master\src\Feature\Maps\code\Sitecore.Feature.Maps.csproj]

**Comment by lautarobonetto** [comment]
Sorry. It was a local issue. There are not bugs here.

**Comment by MknNM** [comment]
@lautarobonetto what was the problem. Im facing the same issue where the Publish-All-Projects falis because kernel.dll is in use.

**Comment by alinulms** [comment]
Set copy local to false on the kernel dll.

**Comment by hfishere** [comment]
Just restart the PC is solved my issue
