### ISSUE TITLE
Cannot set Source property of Image field to Media Library path

### ISSUE THREAD

**Issue by demiurgency** [Sitecore/Habitat#175]
I am learning the Habitat reference site to apply the patterns in my next Sitecore project, and I cannot figure out the proper way to set the Source property of an Image field to a Feature Content Item template.  

Example:  /sitecore/templates/Project/Common/Content Types/Media/Image inherits the Media Image field from /sitecore/templates/Feature/Media/_HasMediaImage.  It seems improper to set the Source field in /sitecore/templates/Feature/Media/_HasMediaImage/Media/MediaImage to a path in the Sitecore media library, as the destination folder is unknown from the Feature layer.  I assume the Media Library path (example: /sitecore/media library/Habitat/Images/Content/) should only be known from the Project layer.

This same issue appears to also apply to setting the Source property of Treelist fields, such as /sitecore/templates/Feature/Metadata/_PageMetadata/Metadata/MetaKeywords, which is set to Project path /sitecore/content/Habitat/Global/Metadata Keywords

**Comment by Eldblom** [comment]
This is a classic problem for multi-site/tenant solutions in Sitecore. How do you set a single field to draw from multiple sources depending on the site context.  
I would suggest posting the question on Sitecore Community of possibly on the new Stack Exhange site http://sitecore.stackexchange.com/ currently in private beta - an invite has been sent.
