### ISSUE TITLE
Add Global Folder as insert options on Site Root Standard values?

### ISSUE THREAD

**Issue by Sen-Gupta** [Sitecore/Habitat#176]
Suggestion:

I think adding Global Folder as insert options on Site Root Standard values makes sense as when ever we will add another Site, we will start with a new Site Root instance and we will need it apart from the 2 already configured insert options.

**Comment by Eldblom** [comment]
The use of the common folder template should be discouraged as specific folder templates allows to greater flexibility and better options for configuration.
See http://helix.sitecore.net/principles/templates/template-types.html#folder-templates
