### ISSUE TITLE
Question about the project structure

### ISSUE THREAD

**Issue by GoranHalvarsson** [Sitecore/Habitat#18]
I was wondering of the setup of the projects, Let say Habitat.Framework.Indexing:
The physical structure is C:\Projects\\Habitat\src\Framework\Indexing and that is cool.
* In folder code you have the actual Project  
* In folder Tests you have the test Project  
* In folder serialization you have the serialized items

So far so good...

But then you you have a bin and obj folder, what is the purpose with those? I mean you also have have a bin and obj folder in the code folder.
Please shed some light on this :-)

**Comment by dashkodo** [comment]
It looks like issue, I'll take it tommorow

Надіслано з iPad

15 нояб. 2015 г. о 14:42 Göran Halvarsson <notifications@github.com> написав(ла):

**Comment by dashkodo** [comment]
Hi Goran,
It looks like old trash from previous solution structure
