### ISSUE TITLE
Site Definition with targetHostname, hostName for multiple domains

### ISSUE THREAD

**Issue by mohit511** [Sitecore/Habitat#181]
We noticed the following when using hostName on site definition -

1) the targetHostName property in SiteDefinition  has "**habitat.**" prefixed which causes the Links to break on the website. We made it work by removing the extra prefix.
2) As Sitecore standard behavior the site is accessible without having to provide hostName or targetHostName if accessed through any binding mapped on hosts file.But with habitat it always enforces to use one of these attributes. 
3) "hostName" attribute on sitedefinition also does not allow pipe delimited domain names. This is standard behavior with default Sitecore instance.

Thanks
Mohit

**Comment by Eldblom** [comment]
Sorry about the delayed reply. This has been resolved - please check the reply for Issue #189
