### ISSUE TITLE
Version conflicts

### ISSUE THREAD

**Issue by Eldblom** [Sitecore/Habitat#184]
When doing a clean build the testing projects creates warnings because of conflicting dependencies.

`  Consider app.config remapping of assembly "Ploeh.AutoFixture, Culture=neutral, PublicKeyToken=b24654c590009d4f" from Version "3.30.0.0" [] to Version "3.47.4.0" [C:\Projects\Habitat\packages\AutoFixture.3.47.4\lib\net40\Ploeh.AutoFixture.dll] to solve conflict and get rid of warning.
  Consider app.config remapping of assembly "xunit.core, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c" from Version "2.0.0.2929" [] to Version "2.1.0.3179" [C:\Projects\Habitat\packages\xunit.extensibility.core.2.1.0\lib\dotnet\xunit.core.dll] to solve conflict and get rid of warning.
  Consider app.config remapping of assembly "NSubstitute, Culture=neutral, PublicKeyToken=92dd2e9066daa5ca" from Version "1.5.0.0" [] to Version "1.10.0.0" [C:\Projects\Habitat\packages\NSubstitute.1.10.0.0\lib\net45\NSubstitute.dll] to solve conflict and get rid of warning.
  C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3247: Found conflicts between different versions of the same dependent assembly. In Visual Studio, double-click this warning (or select it and press Enter) to fix the conflicts; otherwise, add the following binding redirects to the "runtime" node in the application configuration file: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="Ploeh.AutoFixture" culture="neutral" publicKeyToken="b24654c590009d4f" /><bindingRedirect oldVersion="0.0.0.0-3.47.4.0" newVersion="3.47.4.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="xunit.core" culture="neutral" publicKeyToken="8d05b1bb7a6fdb6c" /><bindingRedirect oldVersion="0.0.0.0-2.1.0.3179" newVersion="2.1.0.3179" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="NSubstitute" culture="neutral" publicKeyToken="92dd2e9066daa5ca" /><bindingRedirect oldVersion="0.0.0.0-1.10.0.0" newVersion="1.10.0.0" /></dependentAssembly></assemblyBinding>
`

**Comment by sergeyshushlyapin** [comment]
There are numerous different FakeDb versions installed as well ([1.0.1](https://github.com/Sitecore/Habitat/blob/master/src/Foundation/Accounts/tests/packages.config#L18), [1.1.1](https://github.com/Sitecore/Habitat/blob/master/src/Feature/News/Tests/packages.config#L18), [1.1.2](https://github.com/Sitecore/Habitat/blob/master/src/Feature/Accounts/Tests/packages.config#L18)) despite I updated them all [some time ago](https://github.com/Sitecore/Habitat/pull/109).  Before installing packages it would be nice to *check* the existing versions and *align* them if necessary
