### ISSUE TITLE
Issue "Step 5: Sync-Unicorn"

### ISSUE THREAD

**Issue by plant2442** [Sitecore/Habitat#187]
I  had gotten a issue when I tried to install Habitat for a instance Sitecore follow step by steps on Getting Started.(https://github.com/Sitecore/Habitat/wiki/01-Getting-Started) 
It's taking a long time when run step 5: Sync Unicorn.
Here is the detail screen shot: 
![error](https://cloud.githubusercontent.com/assets/5655030/17319121/9f15ee2a-58b5-11e6-994b-5966020c167a.png)
Anybody can help me explain it.
Thank a lot for your help.

**Comment by Eldblom** [comment]
Can you elaborate a bit, please? What does "a long time mean"?
This step puts all the content from version controlled, serialised files into the Sitecore databases - so depending on your machine config it can take a while.
Does the process actually freeze and never return?

**Comment by plant2442** [comment]
@Eldblom Yeb.I think the process freeze and It never return. It just starting for a long time and never return the result.

**Comment by Eldblom** [comment]
Have you tried syncing using /unicorn.aspx on the website?

**Comment by plant2442** [comment]
@Eldblom I can't access to "../unicorn.aspx" .I got a message "The resource cannot be found."
I also have a error "Could not find configuration node: databases/database[@id='core']" when I try to access to "../sitecore"

**Comment by eduardpaul** [comment]
I'm having the same issue, the step "05-Sync-Unicorn" hangs without any log (waited for more than hour). Tried to access de /unicorn.aspx and have same strange warnings. ¿any idea? I can't find anything.
Also it's meaningful that it is my first time installing sitecore.
![warning](https://cloud.githubusercontent.com/assets/1370426/18418196/37543fd8-7842-11e6-8378-fcbc96f60ffb.png)

**Comment by eduardpaul** [comment]
Well it was simple: security warning of powershell that can't be seen from visual studio task runner.
After get it working, now i'm having the [#191](https://github.com/Sitecore/Habitat/issues/191) issue witch is in same closed state without any tip's 4 noobie's :(
