### ISSUE TITLE
targetHostName in Habitat.Website.config

### ISSUE THREAD

**Issue by Dheer-Rajpoot** [Sitecore/Habitat#189]
Currently the value of **targetHostName** is **habitat.$(rootHostName)** in **Habitat.Website.config**
This value is appending extra habitat in links. $(rootHostName) value is defined in z.Habitat.DevSettings.config 

I think the value of **targetHostName** should be **$(rootHostName)**. 

Below are the my settings:

```
<sc.variable name="sourceFolder" value="D:\SourceCode\HabitatSC\src" />
<sc.variable name="rootHostName" value="habitat.local" />
```

URL of habitat website in local system: http://habitat.local/

Let me know if further information is required from my end.

**Comment by Eldblom** [comment]
The default host name for the development environment has been changed to `habitat.dev.local` - the rootHostName being `dev.local` and the targetHostName setting to `habitat.$(rootHostName)`.   
This means that in a multi-site environment, each site will just have `site.$(rootHostName)` - and we can change the rootHostName in a single file across environments.
