### ISSUE TITLE
Question about adding a project

### ISSUE THREAD

**Issue by GoranHalvarsson** [Sitecore/Habitat#19]
Hello

This is another question about when creating a project. What kind of project type do you guys choose?
1.Is it an empty Web Application, and then you add all the "MVC" stuff from the Nuget Manager. 
2.Or do you create a MVC application and then remove the "unwanted" files.
3.Or are you reusing projects from solution(make a copy)

**Comment by steviemcg** [comment]
1st for me :-)

On 16 Nov 2015, at 09:10, G?ran Halvarsson <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello

This is another question about when creating a project. What kind of project type do you guys choose?
1.Is it an empty Web Application, and then you add all the "MVC" stuff from the Nuget Manager.
2.Or do you create a MVC application and then remove the "unwanted" files.
3.Or are you reusing projects from solution(make a copy)

-

**Comment by Eldblom** [comment]
I typically do #2

**Comment by GoranHalvarsson** [comment]
Thanks guys :-)
