### ISSUE TITLE
Habitat to Sitecore 8.2 ?

### ISSUE THREAD

**Issue by GoranHalvarsson** [Sitecore/Habitat#198]
This is actually not an issue, more a question :-) When will you guys upgrade habitat to Sitecore 8.2 or have a fully working Habitat version in Sitecore 8.2 ?

**Comment by Eldblom** [comment]
There is a branch already working on 8.2. 
https://github.com/Sitecore/Habitat/tree/release/8.2

We are reluctant to merge this with master at this point, as there are some requirements for our demos which is not supported by 8.2 yet - specifically EXM.

**Comment by GoranHalvarsson** [comment]
Thanks, great totally missed that branch :-)

**Comment by sergeyshushlyapin** [comment]
Please note that FakeDb configuration for 8.2 [has been simplified](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/pull/142).

**Comment by isaadansari** [comment]
Please refer to this documentation `https://github.com/Sitecore/Habitat/wiki/01-Getting-Started`

you can easily settle it. the key is the versions. you should have sitecore 8.2 update 5 and WFFM web forms should be installed before you run the gulp task runner.
