### ISSUE TITLE
web.config transforms

### ISSUE THREAD

**Issue by Eldblom** [Sitecore/Habitat#2]
Allow project based changes to web.config without having to include the entire web.config in the project.
Ideas?

**Comment by dashkodo** [comment]
Already done by using microsoft xdt transformation tool

**Comment by GoranHalvarsson** [comment]
I hade some issues with the webconfig after the task runner build. I had to add the webconfig file back to the website proj inorder to make it work

**Comment by dashkodo** [comment]
Please clarify what issues do You have?

**Comment by GoranHalvarsson** [comment]
Sorry for that. Yes after the task runner, it's like the webconfig has been replaced from one of the webconfigs in the projects.

**Comment by GoranHalvarsson** [comment]
Like this:
![webconfig](https://cloud.githubusercontent.com/assets/726479/11300172/3ac6ffb4-8f8d-11e5-9b59-7fbee0882c2b.PNG)

**Comment by dashkodo** [comment]
Are you using latest sources? Looks like outdated, because on the screenshot it is web.config of Accounts module, but right now it has "Build action" property set to "None"
