### ISSUE TITLE
Rendering exception handling?

### ISSUE THREAD

**Issue by steviemcg** [Sitecore/Habitat#20]
This looks interesting: http://vladimirhil.com/2015/11/15/sitecore-rendering-exceptions-handling/

**Comment by nsgocev** [comment]
Steve something that you might also like - https://www.hhogdev.com/blog/2015/june/mvc-rendering-exception-handler.aspx

**Comment by steviemcg** [comment]
I most certainly do!!

**Comment by Eldblom** [comment]
Added to backlog
