### ISSUE TITLE
Static Asset Repository?

### ISSUE THREAD

**Issue by mikg2003** [Sitecore/Habitat#203]
I'm sure I'm missing something with how the assets in Habitat were expected to be used, however here's the problem as I see it:  If you go to any page in Sitecore and add a javascript snippet to the JavascriptCodeTop or bottom fields, it will render on that page.  Perfect.  However, the asset repository and the render assets service are both marked as static.  So, if I go to any other page now, it will also have the script from the previous page render.  Not only that, if anyone else goes to any page, that script will run.  Not to mention, if you have a multisite setup, the script will render on all of those pages too.  It's all because the asset service and repository are static.

**Comment by mzizka** [comment]
I agree, I thought this made very little sense and could even cause security issues. We changed AssetRepository so it uses `HttpContext.Current.Items` instead.

**Comment by Eldblom** [comment]
Thanks for the report. We will fix as soon as possible.
