### ISSUE TITLE
05-Sync-Unicorn issue

### ISSUE THREAD

**Issue by AnnaWang1985** [Sitecore/Habitat#205]
when i run the  05-Sync-Unicorn task, it prompt error message "Command failed: Invoke-WebRequest : The remote name could not be resolved: 'habitat.dev.local'". 
anybody can give me some suggetions?
Thank a lot for your help.

![010101](https://cloud.githubusercontent.com/assets/20471881/18699864/7e67070e-8006-11e6-8e73-830312eb8ace.jpg)

**Comment by AnnaWang1985** [comment]
i can't access the "http://habitat.dev.local/" 
whether i need to set the "127.0.0.1 habitat.dev.local" in host file.
anybody have advice?

**Comment by AnnaWang1985** [comment]
Does anyone here know how to fix the issue?

**Comment by brucedg** [comment]
Check gulp configuration publishing settings etc and make sure hostname is
correct

**Comment by mrunalbrahmbhatt** [comment]
Hi Anna,

Try to update rootHostName parameter.




Thanks & Regards,
Mrunal Brahmbhatt
Skype ID: mrunal.brahmbhatt
Mobile : 0415 64 64 65

**Comment by AnnaWang1985** [comment]
Hi all,
i have updated the rootHostName value, but still cannot resolve the issue.
<sc.variable name="rootHostName" value="Habitat.dev.local" />
![222](https://cloud.githubusercontent.com/assets/20471881/18701374/d4bb501c-800e-11e6-8f28-bdca7799cf7c.jpg)

**Comment by brucedg** [comment]
Is it set correctly in publishing.settings ?

**Comment by mrunalbrahmbhatt** [comment]
https://github.com/Sitecore/Habitat/wiki/01-Getting-Started

Follow step 2

**Comment by AnnaWang1985** [comment]
Fully follow step 2......

**Comment by AnnaWang1985** [comment]
![33](https://cloud.githubusercontent.com/assets/20471881/18702382/0fa41790-8014-11e6-9ae3-8414061c7ac4.jpg)
![44](https://cloud.githubusercontent.com/assets/20471881/18702387/14aae660-8014-11e6-9979-4dde06f4306b.jpg)

**Comment by AnnaWang1985** [comment]
anybody have good new?

**Comment by Simar14** [comment]
Anna,
Run PowerShell with Elevated access:
Run Following command:  Enable-PSRemoting –Force

Then Run your unicorn sync process.

**Comment by AnnaWang1985** [comment]
@Simar14   i excute the commmd, but still shows that error ""Command failed: Invoke-WebRequest : The remote name could not be resolved: 'habitat.dev.local'". "

**Comment by MortazaKamalNourestani** [comment]
Are you using SC8.1 or 8.2?

**Comment by Eldblom** [comment]
@AnnaWang1985 Have you set up the clean Sitecore 8.1 update 3 site in habitat.dev.local as the Getting Started instructions say?

**Comment by AnnaWang1985** [comment]
@MortazaKamalNourestani using SC 8.1

**Comment by AnnaWang1985** [comment]
@Eldblom yes , i set up sitecore 8.1 via the Sitecore Instance Manager (SIM 1.4)

**Comment by AnnaWang1985** [comment]
@Eldblom 
![20161009105610](https://cloud.githubusercontent.com/assets/20471881/19217508/111d8fd0-8e0f-11e6-89b2-d963491d1067.jpg)

**Comment by marcduiker** [comment]
Hi Anna, I notice two things.

The mist important is that the default location for your Sitecore instances in SIM is set to C:\websites\habitat.dev.local. This should be just C:\websites. When you install a new Sitecore instance for Habitat with SIM just enter Habitat.dev.local in the Site name field and the other fields will automatically populated (and don't change them manually).

Secondly the roothost variable should be set to dev.local.

**Comment by akifirfan** [comment]
Hy AnnaWang1985,

Please paste following entry in your hosts file.

127.0.0.1	Habitat.dev.local

Note:
Host file location is:  C:\Windows\System32\drivers\etc\hosts
