### ISSUE TITLE
'Constants' is an ambiguous reference between 'Sitecore.Foundation.Alerts.Constants' and 'Sitecore.Constants'

### ISSUE THREAD

**Issue by MortazaKamalNourestani** [Sitecore/Habitat#209]
Constants.InfoMessageView needs to be prefixed with full namespace  Sitecore.Foundation.Alerts.Constants' 

Server Error in '/' Application.

Compilation Error

Description: An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately. 

```
> Compiler Error Message: CS0104: 'Constants' is an ambiguous reference between 'Sitecore.Foundation.Alerts.Constants' and 'Sitecore.Constants'
> 
> Source Error:
> 
> 
> Line 13:   if (info != null)
> Line 14:   {
> Line 15:     Html.RenderPartial(Constants.InfoMessageView, info);
> Line 16:   }
> Line 17:   <div class="form-group @Html.ValidationErrorFor(x => x.FirstName, "has-error")">
> 
> Source File: D:\Projects\Sitecore82\Website\Views\Accounts\EditProfile.cshtml    Line: 15 
```

**Comment by Eldblom** [comment]
Please include more information on where and how you encounter this error. Is this in Visual Studio? When browsing the site?
