### ISSUE TITLE
05-Sync-Unicorn issue : Automated tool authentication failed

### ISSUE THREAD

**Issue by giftsonjebin** [Sitecore/Habitat#211]
When running 05-Sync-Unicorn gulp task, it fails with attached error.
![error](https://cloud.githubusercontent.com/assets/21095346/19065111/7eb298a8-89c6-11e6-9f3f-5fcc7ac2e5c1.JPG)

I've ran this task in the past months, and it completed without any issues.
Unicorn.UI.config is intact and was not modified.

**Comment by yalahyane** [comment]
Which Sitecore version are you using?



On Tue, Oct 4, 2016 at 3:10 AM -0400, "giftsonjebin" <notifications@github.com<mailto:notifications@github.com>> wrote:


When running 05-Sync-Unicorn gulp task, it fails with attached error.
[error]<https://cloud.githubusercontent.com/assets/21095346/19065111/7eb298a8-89c6-11e6-9f3f-5fcc7ac2e5c1.JPG>

I've ran this task in the past months, and it completed without any issues.
Unicorn.UI.config is intact and was not modified.

-

**Comment by giftsonjebin** [comment]
I'm using Sitecore 8.1 an vanilla Habitat

**Comment by yalahyane** [comment]
Seems like an unauthorized access error.
Did you look into the logs if you have some more details?
Just to be sure, are you running gulp from an elevated command window?

**Comment by giftsonjebin** [comment]
Thanks for your response. I'm using Visual Studio's Task Runner, with VS running as Administrator. 
Same issue  appears in Unicorn's Github page (https://github.com/kamsar/Unicorn/issues/172) as well, but without any solution.
I've installed Habitat successfully in the past, so I assume this issue might be due to any of the recent changes.

**Comment by jeeby** [comment]
I have the exact same problem... 

Sitecore 8.1 Update 3
Unicorn 3.1.7 (tried to upgrade to 3.2.0 - same thing)
Habitat (at commit b39d6ddc2e1eaa82acc2ceae750be925a217f25d)
Running via Task Runner in VS
VS running as administrator

It does a partial sync, but fails for some of it.

Starts off with an error, then continues to sync...

`[12:53:13] Starting '05-Sync-Unicorn'...
siteHostName: http://deephelix.dev.local
C:\DATA\Deepend\Deepend.Sc\scripts\unicorn.js:36
    if (err !== null) throw err;
                            ^
Error: Command failed: Invoke-WebRequest : Sync Unicorn
Info: Foundation.Serialization is being synced.
Info: 
Info: Foundation.Serialization sync complete: 24 items evaluated, 0 items modified (0 added, 0 updated, 0 recycled) in 
361ms (~15.1ms/item).`

A few features and foundations sync okay, then this error:

`Error: 2 errors occurred during deserialization. Earlier log messages for items below should be ignored; an error 
occurred that was retried and failed to correct.master:/sitecore/system/Modules/Web Forms for 
Marketers/Settings/Actions/Save Actions/Register an Outcome (90538392-5648-4326-b506-e1913ed1daa8)C:\DATA\Deepend\Deepe
nd.Sc\src\Foundation\forms\serialization\Foundation.Forms.WffmActions.RegisterOutcome\Register an Outcome.yml&gt; 
ParentItemNotFoundException: Exception of type 'Sitecore.Data.Serialization.Exceptions.ParentItemNotFoundException' 
was thrown.master:/sitecore/layout/Renderings/Modules/Web Forms for Marketers/Mvc Form (f2cca16d-7524-4e99-8ee0-78ff639
4a3b3)C:\DATA\Deepend\Deepend.Sc\src\Foundation\forms\serialization\Foundation.Forms.Renderings.MvcForm\Mvc 
Form.yml&gt; ParentItemNotFoundException: Exception of type 
'Sitecore.Data.Serialization.Exceptions.ParentItemNotFoundException' was thrown.For full stack traces of each 
exception, see the Sitecore logs.
Info: 
Info: Completed.
At C:\DATA\Deepend\Deepend.Sc\scripts\Unicorn\Unicorn.psm1:43 char:12
+ ...   $result = Invoke-WebRequest -Uri $url -Headers @{ "X-MC-MAC" = $sig ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
Process terminated with code 8.`

I'd LOVE to resolve this ASAP.  I've worked around it by syncing each config manually in /unicorn.aspx, but this automated sync would be the final piece in the puzzle of getting Habitat up and running (it's been a hard slog!)

Thanks heaps
Greg

**Comment by jeeby** [comment]
Resolved!  **Needs Web Forms for Marketers** to be installed.  Looking goooooood now :)

**Comment by giftsonjebin** [comment]
Glad it worked for you! 
However, I did install WFFM after initially setting up my sitecore instance, and I do have WFFM dlls available on my website project.
As I mentioned in my original post, I have setup habitat a few times before without any issues.
Did you perform any other steps as part of WFFM install, apart from whats specified in the installation instructions?

**Comment by jeeby** [comment]
Hey @giftsonjebin 

I don't think it's the WFFM DLLs that are required as much as the actual content items created by the installer.. are you sure it installed correctly?  Check in Sitecore and make sure the content items created by the installer are actually in there.

Is your error exactly the same as mine?  If you go to /unicorn.aspx and run each configuration (foundation ones first, then features, then project), is Forms the only one that fails?  If so, this was my solution.. if not, then you may have something else that needs attention.

**Comment by giftsonjebin** [comment]
Thanks for your response.

I don't see any issues with Content items created by the installer, and I was able to access the new site earlier.

However, after this gulp task failed, I'm getting layout not found error when trying to browse the site (Sitecore admin page still works fine). Here's the error information from sitecore logs. Not sure if this is related to Unicorn sync issue.
**Authentication on CES Discovery service failed.**

Also, I'm not able to manually reserialize any items from Unicorn.aspx page, as I receive errors similar to the ones below (Even when following the order Foundation --> Features --> Project).
_**Foundation.LocalDatasource is being reserialized.
[D] Clearing existing items from Serialization File System Data Store (if any)
Unable to resolve root source item for predicate root path master:/sitecore/templates/Foundation/LocalDatasource. It has been skipped.
Unable to resolve root source item for predicate root path master:/sitecore/templates/System/Layout/Sections/Rendering Options/Editor Options/Supports Local Datasource. It has been skipped.**_

**Comment by jeeby** [comment]
What value did you put in the sourceFolder variable in z.Habitat.DevSettings.config ?  I was getting similar errors when I put the git source folder, whereas what it really wanted was that folder with /src on the end (so the base folder of the actual source code, not the repo). 

Took me a while to find that little nugget.. hope that's your issue too.

**Comment by giftsonjebin** [comment]
Thanks for your suggestion. Unfortunately, all config changes point to the right path.

**Comment by jeeby** [comment]
So you have /src on the end of that path?

**Comment by giftsonjebin** [comment]
Yes, that's correct. I just removed my sitecore instance, and starting afresh. Will see if that works fine.
Thanks for your help!

**Comment by jeeby** [comment]
Also check the version you install... i had issues when i installed a newer version of sitecore than the nuget packages imported in the solution.  I'm now working with Sitecore 8.1 Update 3 (which is the one that Habitat seems to be built on), and will update to 8.2 later (update Sitecore, and all the nuget packages).

**Comment by Eldblom** [comment]
@giftsonjebin Please check your publishsettings.targets file. The publishUrl can not have a trailing slash.

**Comment by giftsonjebin** [comment]
Thank you very much Thomas, for your help with this issue.
I assume publishUrl might be the cause of failure.
I reconfigured Habitat from scratch, and it worked perfectly.

Thanks again for your help!!!

**Comment by nickwesselman** [comment]
@toshi1989 For troubleshooting, please use Sitecore Stackexchange or Slack. GitHub should be limited to new bug reports only.

**Comment by VaradrajKini** [comment]
@toshi1989 update the Powershell script that contains Sync-Unicorn function. See if the below one works for you. My guess is that you get this error when you have used new version of Unicorn/Habitat but your still using the old script.

https://raw.githubusercontent.com/Sitecore/Habitat/master/scripts/Unicorn/Unicorn.psm1
