### ISSUE TITLE
Could not find configuration node: databases/database[@id='master']

### ISSUE THREAD

**Issue by AnnaWang1985** [Sitecore/Habitat#219]
when i run 05-Sync-Unicorn, the Error: Command failed: Invoke-WebRequest : Sync Unicorn Info: Foundation.Serialization is being synced. Error: 42 errors occurred during deserialization.
and when i access http://habitat.dev.local/, the error: Could not find configuration node: databases/database[@id='master']

how to fix the issues? anybody ?Thank you very much.
![20161009164926](https://cloud.githubusercontent.com/assets/20471881/19219273/8b47da36-8e41-11e6-8b8e-2b4103eccbab.jpg)

![20161009165652](https://cloud.githubusercontent.com/assets/20471881/19219282/cacd8bd8-8e41-11e6-8558-b4b48f1700af.jpg)

**Comment by marcduiker** [comment]
Please read my comment in your previous issue: https://github.com/Sitecore/Habitat/issues/205

**Comment by Eldblom** [comment]
@AnnaWang1985 Please check your settings - as per step 2 in the [Gettings Started instructions](https://github.com/Sitecore/Habitat/wiki/01-Getting-Started). If you are using other locations or domains, the settings have to be correct. Also be aware of including or omitting trailing slashes as per the defaults.

**Comment by AnnaWang1985** [comment]
@marcduiker  @Eldblom  thanks for your answer.  I try to set the default location for my Sitecore instances in SIM.  and then run the default task in task runner explorer,  i get the error message until 05-Sync-Unicorn.  I attach some screenshots,  Do I need to change something? i don't have a clue. could you help me. Thank you.
![new1](https://cloud.githubusercontent.com/assets/20471881/19225553/38bb5190-8ed1-11e6-9a6f-f928550dcbb7.jpg)
![new2](https://cloud.githubusercontent.com/assets/20471881/19225651/eb44b698-8ed2-11e6-9e32-977f659a07fa.jpg)
![new3](https://cloud.githubusercontent.com/assets/20471881/19225709/86089f5a-8ed3-11e6-898f-b063b6a93b93.jpg)
![new4](https://cloud.githubusercontent.com/assets/20471881/19225720/9e9c2ce4-8ed3-11e6-9aff-702fcdb8fba5.jpg)

**Comment by Eldblom** [comment]
Sorry, I closed this a bit early.  
Can you run Unicorn via http://habitat.dev.local/unicorn.aspx?verb=Sync ?

**Comment by AnnaWang1985** [comment]
@Eldblom  After I try to access the url http://habitat.dev.local/unicorn.aspx?verb=Sync. The following screen is shown.

![new7](https://cloud.githubusercontent.com/assets/20471881/19226364/ccabcf3c-8edc-11e6-97dd-31a220f9ceba.jpg)

**Comment by Eldblom** [comment]
Looks like a general configuration error. Can you log into Sitecore itself?
I would try to pull the latest code from GitHub, clean the local repository and do a fresh install and build.

Best Regards,
Thomas Eldblom

On 10 Oct. 2016, at 2:32 pm, Anna <notifications@github.com<mailto:notifications@github.com>> wrote:


@Eldblom<https://github.com/Eldblom> After I try to access the url http://habitat.dev.local/unicorn.aspx?verb=Sync. The following screen is shown.

[new7]<https://cloud.githubusercontent.com/assets/20471881/19226364/ccabcf3c-8edc-11e6-97dd-31a220f9ceba.jpg>

-

**Comment by AnnaWang1985** [comment]
@Eldblom  After I set up the sitecore instance via SIM1.4 , i can access the http://habitat.dev.local/ and  I can also log the sitecore. but After run default task,  and then access the website and sitecore,  the error message is shown. 'Could not find configuration node: databases/database[@id='master']' , BTW, yesterday i pulled the latest code.

**Comment by Eldblom** [comment]
Using SIM, could you attach the web.config.result.xml file, please? (In SIM, select the site, click the drop down on “Config Files” and click web.config.result.xml).

Best Regards,

Thomas Eldblom
Sr Technical Manager // Product Marketing
the@sitecore.net<mailto:the@sitecore.net>
+61 (0)4 7754 5839

**Comment by AnnaWang1985** [comment]
master database missing
