### ISSUE TITLE
04-Apply-Xml-Transform fails

### ISSUE THREAD

**Issue by WizX20** [Sitecore/Habitat#220]
**Importance:**  
* **Normal** (I have a workaround, but it would be nice to fix it)  

**Description:**  
`[15:53:20] Using gulpfile D:\Repos\Sitecore\Habitat\Repository\Habitat\Gulpfile.js
[15:53:20] Starting '04-Apply-Xml-Transform'...
[15:53:21] Applying configuration transform: D:\Repos\Sitecore\Habitat\Repository\Habitat\src\Foundation\Installer\code\web.config.transform
[15:53:22] Using automatic maxcpucount
D:\Repos\Sitecore\Habitat\Repository\Habitat\applytransform.targets(14,5): error : Could not open Source file: Could not find a part of the path 'C:\websites\Habitat.dev.local\Website\web.config'.
[15:53:22] { [Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c ""C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "D:\Repos\Sitecore\Habitat\Repository\Habitat\applytransform.targets" "/target:ApplyTransform" /verbosity:minimal /toolsversion:14.0 /nologo /maxcpucount /property:Configuration="Debug" /property:WebConfigToTransform="C:\websites\Habitat.dev.local\Website" /property:TransformFile="D:\Repos\Sitecore\Habitat\Repository\Habitat\src\Foundation\Installer\code\web.config.transform" /property:FileToTransform="web.config""
error!
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe /s /c ""C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\MSBuild.exe" "D:\\Repos\\Sitecore\\Habitat\\Repository\\Habitat\\applytransform.targets" "/target:ApplyTransform" /verbosity:minimal /toolsversion:14.0 /nologo /maxcpucount /property:Configuration="Debug" /property:WebConfigToTransform="C:\\websites\\Habitat.dev.local\\Website" /property:TransformFile="D:\\Repos\\Sitecore\\Habitat\\Repository\\Habitat\\src\\Foundation\\Installer\\code\\web.config.transform" /property:FileToTransform="web.config""' }
[15:53:22] Build failed!
[15:53:22] '04-Apply-Xml-Transform' errored after 2.21 s
[15:53:22] Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c ""C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "D:\Repos\Sitecore\Habitat\Repository\Habitat\applytransform.targets" "/target:ApplyTransform" /verbosity:minimal /toolsversion:14.0 /nologo /maxcpucount /property:Configuration="Debug" /property:WebConfigToTransform="C:\websites\Habitat.dev.local\Website" /property:TransformFile="D:\Repos\Sitecore\Habitat\Repository\Habitat\src\Foundation\Installer\code\web.config.transform" /property:FileToTransform="web.config""
    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
Process terminated with code 1.`

**Scenario:**  
1. Download Habitat
2. Run node install
3. Open visual studio (2015) and run default task

**Information:**
MsBuild.exe is present in the mentioned location, also the web.config and web.config.transform are present. All the resources (visual studio extensions) needed for Habitat are installed.
Running Sitecore 8.2 release

**Comment by yalahyane** [comment]
Do you have a valid sitecore instance installed under C:\websites\Habitat.dev.local ?

**Comment by WizX20** [comment]
Hi, no I did not, sorry. I changed the path to D:\websites\Habitat.dev.local where I installed Sitecore 8.2 using SIM, but the issue remains.

**Comment by yalahyane** [comment]
When you say you changed the path, you mean in  gulp-config.js file?

**Comment by WizX20** [comment]
Yes.

**Comment by WizX20** [comment]
Ok. I've set the verbosity level to diag[nostic]:
`09:39:25.134     1>Building with tools version "14.0".
09:39:25.135     1>Target "ApplyTransform: (TargetId:2)" in project "D:\Repos\Sitecore\Habitat\Repository\Habitat\applytransform.targets" (entry point):
                   Added Item(s): Transform=D:\Repos\Sitecore\Habitat\Repository\Habitat\src\Foundation\Installer\code\web.config.transform
                   Added Item(s): 
                       ConfigsToTransform=
                           web.config
                                   TransformPath=D:\Repos\Sitecore\Habitat\Repository\Habitat\src\Foundation\Installer\code\web.config.transform
                   Using "Message" task from assembly "Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
                   Task "Message" (TaskId:2)
                     Task Parameter:Text=web.config (TaskId:2)
                     web.config (TaskId:2)
                   Done executing task "Message". (TaskId:2)
                   Task "Message" (TaskId:3)
                     Task Parameter:Text=D:\Repos\Sitecore\Habitat\Repository\Habitat\src\Foundation\Installer\code\web.config.transform (TaskId:3)
                     D:\Repos\Sitecore\Habitat\Repository\Habitat\src\Foundation\Installer\code\web.config.transform (TaskId:3)
                   Done executing task "Message". (TaskId:3)
                   Using "TransformXml" task from assembly "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.Web.Publishing.Tasks.dll".
                   Task "TransformXml" (TaskId:4)
                     Task Parameter:Source='D:\Websites\Habitat.dev.local\Website\web.config (TaskId:4)
                     Task Parameter:Transform=D:\Repos\Sitecore\Habitat\Repository\Habitat\src\Foundation\Installer\code\web.config.transform (TaskId:4)
                     Task Parameter:Destination='D:\Websites\Habitat.dev.local\Website\web.config (TaskId:4)
                     Transforming Source File: 'D:\Websites\Habitat.dev.local\Website\web.config (TaskId:4)
09:39:25.227     1>D:\Repos\Sitecore\Habitat\Repository\Habitat\applytransform.targets(14,5): error : Could not open Source file: The given path's format is not supported.
                     Transformation failed (TaskId:4)
                   Done executing task "TransformXml" -- FAILED. (TaskId:4)
09:39:25.228     1>Done building target "ApplyTransform" in project "applytransform.targets" -- FAILED.: (TargetId:2)
09:39:25.228     1>Done Building Project "D:\Repos\Sitecore\Habitat\Repository\Habitat\applytransform.targets" (ApplyTransform target(s)) -- FAILED.
Deferred Messages
09:39:25.229     0>
Detailed Build Summary
======================
     (TaskId:0)
                     
                     ============================== Build Hierarchy (IDs represent configurations) =====================================================
                     Id                  : Exclusive Time   Total Time   Path (Targets)
                     ----------------------------------------------------------------------------------------------------------------------------------- (TaskId:0)
                     0                   : 0.103s           0.103s       D:\Repos\Sitecore\Habitat\Repository\Habitat\applytransform.targets (ApplyTransform)  (TaskId:0)
                     
                     ============================== Node Utilization (IDs represent configurations) ====================================================
                     Timestamp:            1        Duration   Cumulative
                     ----------------------------------------------------------------------------------------------------------------------------------- (TaskId:0)
                     636118547651257338:   0        0,103s     0,103s ## (TaskId:0)
                     -----------------------------------------------------------------------------------------------------------------------------------
                     Utilization:          100,0    Average Utilization: 100,0 (TaskId:0)
Project Performance Summary:
       94 ms  D:\Repos\Sitecore\Habitat\Repository\Habitat\applytransform.targets   1 calls
                 94 ms  ApplyTransform                             1 calls
Target Performance Summary:
       92 ms  ApplyTransform                             1 calls
Task Performance Summary:
        2 ms  Message                                    2 calls
       32 ms  TransformXml                               1 calls
Build FAILED.
                   "D:\Repos\Sitecore\Habitat\Repository\Habitat\applytransform.targets" (ApplyTransform target) (1) ->
                   (ApplyTransform target) -> 
                     D:\Repos\Sitecore\Habitat\Repository\Habitat\applytransform.targets(14,5): error : Could not open Source file: The given path's format is not supported.`

**Comment by WizX20** [comment]
Ok, it was a typo, there was a single quote in the path. Closing the issue.

**Comment by prem16** [comment]
I am facing the same problem,even i have no typo.

**Comment by nickwesselman** [comment]
@prem16 This issue is quite old and there have been changes to how the transforms work since then. We are also limiting GitHub to bug reports and feature requests. I would recommend submitting a question to Sitecore Stackexchange with the error message and any other relevant details about your environment. We monitor habitat-tagged questions there. Thanks!

**Comment by prem16** [comment]
Thanks nickwesselman .
