### ISSUE TITLE
Could not create instance of type: Sitecore.Data.Database. No matching constructor was found.

### ISSUE THREAD

**Issue by JagatheeshMenon2016** [Sitecore/Habitat#226]
Hi Team,

I have created fresh instance of sitecore and followed all the steps that are given in the Wiki, however soon after running the gulp-command(04-Apply-XML-transformation) I am getting the error No matching constructor was found. Attached is the error snapshot for further reference.
![error](https://cloud.githubusercontent.com/assets/20538181/19514433/14bacf90-9611-11e6-9342-1cfdc7e6c40e.jpg)
 
Any help on  this would be really great full.

I have also followed the below url but it didn't do much good error still persist. 
https://sitecorebasics.wordpress.com/2014/06/04/could-not-create-instance-of-type-sitecore-data-database-no-matching-constructor-was-found/

**Comment by yalahyane** [comment]
Which version of Sitecore are you using?

**Comment by JagatheeshMenon2016** [comment]
8.1 update 2

**Comment by yalahyane** [comment]
Habitat is now updated to 8.2. There's a release/8.1 branch that you can use with 8.1 for now, but eventually I think this branch will be removed.
Regards

**Comment by GoranHalvarsson** [comment]
Hey guys
Great job with Habitat !!

I think its important that you guys still have the Sitecore 8.1 branch. 
Please don't remove it

**Comment by Eldblom** [comment]
@GoranHalvarsson We will not be supporting and developing on multiple versions. We have tagged releases through the last year which links to certain versions, e.g. [Version 1.2](https://github.com/Sitecore/Habitat/releases/tag/1.2) supports version 8.1u3.
