### ISSUE TITLE
Consider defining ID "constant" containers as classes over structures

### ISSUE THREAD

**Issue by jswindell** [Sitecore/Habitat#227]
When I came across the "struct" declarations throughout many Template.cs files, I immediately thought of this:

[Choosing Between Class and Struct](https://msdn.microsoft.com/en-us/library/ms229017%28v=vs.110%29.aspx)

After all, they only contain [Sitecore Data ID](https://sdn.sitecore.net/doc/api%205.1.1/Sitecore.Data.ID.html)s anyway.

Thoughts?

**Comment by Eldblom** [comment]
Thanks @jswindell. 
The reason structs were chosen was to clearly indicate that the Templates are mere constant holders and make developers stop and think before extending the classes with logic etc.
We dont see any reasons to change to classes.

**Comment by jswindell** [comment]
Well, there's nothing to say that developers couldn't try to extend structs either, but thanks for responding.

I'll close this out.
