### ISSUE TITLE
Unicorn default task always fails with weird errors

### ISSUE THREAD

**Issue by joshuasanderson** [Sitecore/Habitat#228]
I followed all the steps for installing the Habitat website and once the default Task Runner job got to the 05-Sync-Unicorn task, it fails. Here are some of the errors that it dumps in the logs during the execution:

```
INNER EXCEPTION
master:/sitecore/content/Habitat/Home/About Habitat/Introduction/_Local/Habitat Introduction (67e5f37f-adf9-4044-9a02-fbe3e99b5a7a) (Rainbow.Storage.Sc.Deserialization.DeserializationException)
No stack trace available.
INNER EXCEPTION
Exception of type 'Sitecore.Data.Serialization.Exceptions.ParentItemNotFoundException' was thrown. (Sitecore.Data.Serialization.Exceptions.ParentItemNotFoundException)

INNER EXCEPTION
master:/sitecore/content/Habitat/Home/Modules/Feature/News/News/2015/08/24/17/57/Best In Class (88d7f189-43af-4704-94ea-daa482f9dba5) (Rainbow.Storage.Sc.Deserialization.DeserializationException)
No stack trace available.
INNER EXCEPTION
The fields c464d2d7-3382-428a-bcdf-0963c60ba0e3 (likely NewsDate), 3437eaac-6ee8-460b-a33d-da1f714b5a93 (likely NewsImage), 801612c7-5e98-4e3c-80d2-a34d0eebcbda (likely NewsBody), 9d08271a-1672-44dd-b7ef-0a6ec34fcba7 (likely NewsSummary), bd9ecd4a-c0b0-4233-a3cd-d995519ac87b (likely NewsTitle) are not present in Sitecore on the News Article template. (Rainbow.Storage.Sc.Deserialization.TemplateMissingFieldException)

INNER EXCEPTION
master:/sitecore/content/Habitat/Home/Modules/Feature/News/News/2015/08/24/17/57/Experience Management (844a7337-2020-4c2e-912e-7651930fe179) (Rainbow.Storage.Sc.Deserialization.DeserializationException)
No stack trace available.
INNER EXCEPTION
The fields c464d2d7-3382-428a-bcdf-0963c60ba0e3 (likely NewsDate), 3437eaac-6ee8-460b-a33d-da1f714b5a93 (likely NewsImage), 801612c7-5e98-4e3c-80d2-a34d0eebcbda (likely NewsBody), 9d08271a-1672-44dd-b7ef-0a6ec34fcba7 (likely NewsSummary), bd9ecd4a-c0b0-4233-a3cd-d995519ac87b (likely NewsTitle), 3437eaac-6ee8-460b-a33d-da1f714b5a93 (likely NewsImage), 801612c7-5e98-4e3c-80d2-a34d0eebcbda (likely NewsBody), 9d08271a-1672-44dd-b7ef-0a6ec34fcba7 (likely NewsSummary), bd9ecd4a-c0b0-4233-a3cd-d995519ac87b (likely NewsTitle) are not present in Sitecore on the News Article template. (Rainbow.Storage.Sc.Deserialization.TemplateMissingFieldException)

INNER EXCEPTION
master:/sitecore/content/Habitat/Home/Modules/Feature/News/News/2015/08/24/17/57/New version (b415f846-5eed-409c-b6d8-c23bab52d502) (Rainbow.Storage.Sc.Deserialization.DeserializationException)
No stack trace available.
INNER EXCEPTION
The fields c464d2d7-3382-428a-bcdf-0963c60ba0e3 (likely NewsDate), 3437eaac-6ee8-460b-a33d-da1f714b5a93 (likely NewsImage), 801612c7-5e98-4e3c-80d2-a34d0eebcbda (likely NewsBody), 9d08271a-1672-44dd-b7ef-0a6ec34fcba7 (likely NewsSummary), bd9ecd4a-c0b0-4233-a3cd-d995519ac87b (likely NewsTitle) are not present in Sitecore on the News Article template. (Rainbow.Storage.Sc.Deserialization.TemplateMissingFieldException)

INNER EXCEPTION
master:/sitecore/content/Habitat/Home/Modules/Feature/News/News/2015/08/24/17/57/Best In Class/_Local (8481ebe7-0c85-4f68-904f-9a4e699e9d2c) (Rainbow.Storage.Sc.Deserialization.DeserializationException)
```

I had a fresh 8.2 install that worked fine prior to going through and opening the solution from this repo, modifying the 3 config files I have to and then ultimately running the default task.

I really would love to know what is going on with this as I don't understand how fields could be missing on the data templates provided by the code in the repo.

Thank you!

**Comment by yalahyane** [comment]
Hi Joshua,
I just installed a fresh version of Habitat with Sitecore 8.2 and WFFM 8.2, and it worked fine for me.
Just to be sure, did you install WFFM 8.2?
Can you please send me a copy of your gulp-config.js, publishsettings.targets and z.Habitat.DevSettings.config ?

Thanks.

Yassine

**Comment by joshuasanderson** [comment]
Yeah I have the latest installed for both. Attached is the zip with those files.

Thanks
[configs.zip](https://github.com/Sitecore/Habitat/files/556339/configs.zip)

**Comment by yalahyane** [comment]
Hi Joshua,
I see in you gulp-config instanceroot =C:\\inetpub\\wwwroot\\HabitatDemo
But in the other file you're using HabitatDemo82 as instance name.
The root instance shouldn't be C:\\inetpub\\wwwroot\\HabitatDemo82 instead?

Regards,

Yassine

**Comment by joshuasanderson** [comment]
The HabitatDemo82 is my binding to the local website. It's what I use to navigate to the website in the browser. In IIS for that website, the physical path points to C:\inetpub\wwwroot\HabitatDemo\Website

I guess I'm not sure which one I should use for instance name and instance root?

**Comment by yalahyane** [comment]
So your instanceName is HabitatDemo, and HabitatDemo82 is the binding you use?
In that case i would use HabitatDemo as rootHostName and in the PublishUrl.
To be sure you have the right rootHostName go to http://HabitatDemo/sitecore/admin/showconfig.aspx and look for rootHostName variable...

**Comment by yalahyane** [comment]
Do you still have the issue?

**Comment by joshuasanderson** [comment]
Hello - no I did a complete fresh install again, this time using the SIM installer instead of just downloading a copy of Sitecore 8.2 from the website and creating a website that way.

That seemed to work fine... Really don't know what was going on with my other website.

Thank you for the help today! I will close this.

**Comment by yalahyane** [comment]
You're welcome. Glad it's working for you now:-)
Regards.
