### ISSUE TITLE
Compile Magic

### ISSUE THREAD

**Issue by timbuktuuu** [Sitecore/Habitat#241]
Hi,

that's not an Issue, but i don't get the magic behind compile SCSS to CSS. How is it in the gulp Workflow implemented?

I can't figure it out 😡

**Comment by Eldblom** [comment]
Despite what you would naturally think, the gulp scripts are actually not used to handle the scripts or stylesheets of the solution - just the build and publish process.  
The Foundation.Theming project uses the Visual Studio Web Essentials and Web Compiler to compile scss and bundle the javascript: https://github.com/Sitecore/Habitat/wiki/02-Resources
