### ISSUE TITLE
Renaming top-level pages breaks Anonymous

### ISSUE THREAD

**Issue by pilkentonc** [Sitecore/Habitat#242]
In re-using Habitat's structure to build new instances, I've come across an issue that when changing the Item Name for any top-level Page under Home, a Basic Authentication popup shows from IIS.  This also happens when an existing Page is duplicated or a new one is created.

There doesn't appear to be a config anywhere limiting Habitat to just what was original as everything under the root should be anonymous and able to be changed.  Both IIS and Access Viewer show the items with Anonymous still set correctly.
![sitecore_habitat_toppage_errors_1](https://cloud.githubusercontent.com/assets/15385913/20539216/3b7d7f26-b0c2-11e6-8ad3-01d2ddb9e80e.jpg)
![sitecore_habitat_toppage_errors2](https://cloud.githubusercontent.com/assets/15385913/20539215/3b7c676c-b0c2-11e6-92a6-c76b7a946aa7.jpg)

Assistance around this bug is needed.

**Comment by Eldblom** [comment]
Sorry, we cannot recreate this bug. Please revisit your IIS settings.
