### ISSUE TITLE
Gulp Nuget-restore error

### ISSUE THREAD

**Issue by danteciambella** [Sitecore/Habitat#244]
I'm tring to install Habitat but when I try to run the default task the nuget-restore give me the following error message. What I'm missing?

Error: Command failed: Unable to find version '1.4.0' of package 'Rainbow.Storage.Yaml'.
Unable to find version '3.3.1' of package 'Unicorn.Users.Core'.
Unable to find version '1.11.326' of package 'BuildWebCompiler'.
Unable to find version '3.3.1' of package 'Unicorn.Roles'.
Unable to find version '1.3.1' of package 'Sitecore.FakeDb.AutoFixture'.
Unable to find version '1.0.0' of package 'Microsoft.Extensions.DependencyInjection.Abstractions'.
Unable to find version '1.0.0' of package 'Microsoft.Extensions.DependencyInjection'.
Unable to find version '3.49.0' of package 'AutoFixture.AutoNSubstitute'.
Unable to find version '3.3.1' of package 'Unicorn.Core'.
Unable to find version '3.3.1' of package 'Unicorn.Users'.
Unable to find version '1.3.1' of package 'Sitecore.FakeDb.NSubstitute'.
Unable to find version '1.4.0' of package 'Rainbow'.
Process terminated with code 8.
Unable to find version '3.0.3' of package 'Lucene.Net'.
Unable to find version '3.3.1' of package 'Unicorn.Roles.Core'.
Unable to find version '1.10.0' of package 'mongocsharpdriver'.
Unable to find version '1.8.0.1549' of package 'xunit.extensions'.
Unable to find version '3.49.0' of package 'AutoFixture'.
Unable to find version '3.3.1' of package 'Unicorn'.
Unable to find version '11.0.2100.61' of package 'Microsoft.SqlServer.Scripting'.
Unable to find version '1.4.0' of package 'Rainbow.Core'.
Unable to find version '1.2.2.2' of package 'MicroCHAP'.
Unable to find version '1.4.0' of package 'Rainbow.Storage.Sc'.
Unable to find version '4.7.0' of package 'FluentAssertions'.
Unable to find version '3.49.0' of package 'AutoFixture.Xunit2'.
Unable to find version '1.10.0' of package 'NSubstitute'.
Unable to find version '1.3.1' of package 'Sitecore.FakeDb'.
Unable to find version '3.47.4' of package 'AutoFixture.Xunit'.
    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

Thanks.

**Comment by Eldblom** [comment]
All those packages should be accessible on the standard nuget feed. I'm guessing your command line cant access the internet?
Works fine on my local machine and on our build server.

**Comment by danteciambella** [comment]
Hi Thomas, thank you very much for your replay. Now I installed all the package without any problem, may be that we had some network problem Yesterday morning.
