### ISSUE TITLE
Registration failed

### ISSUE THREAD

**Issue by DheerajP** [Sitecore/Habitat#248]
I am on sitecore 8.2 initial release.

while trying to register i ended up with below error:

**One or more exceptions occurred while processing the subscribers to the 'user:created' event.**
`Description: An unhandled exception occurred. 
Exception Details: System.AggregateException: One or more exceptions occurred while processing the subscribers to the 'user:created' event.
Source Error: 
Line 65:             Assert.IsNotNullOrEmpty(fullName, "Can't retrieve full userName");
Line 66: 
Line 67:             var user = User.Create(fullName, password);
Line 68:             user.Profile.Email = email;
Line 69:             if (!string.IsNullOrEmpty(profileId))
Source File: C:\Projects\Habitat\src\feature\Accounts\code\Repositories\AccountRepository.cs    Line: 67 
Stack Trace: 
[AggregateException: One or more exceptions occurred while processing the subscribers to the 'user:created' event.]
   Sitecore.Events.EventSubscribers.RaiseEvent(String eventName, Object[] parameters, EventResult result) +1945
   Sitecore.Events.Event.RaiseEvent(String eventName, Object[] parameters) +389
   Sitecore.Security.SitecoreMembershipProvider.CreateUser(String username, String password, String email, String passwordQuestion, String passwordAnswer, Boolean isApproved, Object providerUserKey, MembershipCreateStatus& status) +366
   System.Web.Security.Membership.CreateUser(String username, String password, String email, String passwordQuestion, String passwordAnswer, Boolean isApproved, Object providerUserKey, MembershipCreateStatus& status) +331
   System.Web.Security.Membership.CreateUser(String username, String password, String email) +54
   Sitecore.Security.Accounts.User.Create(String userName, String password) +68
   Sitecore.Feature.Accounts.Repositories.AccountRepository.RegisterUser(String email, String password, String profileId) in C:\Projects\Habitat\src\feature\Accounts\code\Repositories\AccountRepository.cs:67
   Sitecore.Feature.Accounts.Controllers.AccountsController.Register(RegistrationInfo registrationInfo) in C:\Projects\Habitat\src\feature\Accounts\code\Controllers\AccountsController.cs:63
   lambda_method(Closure , ControllerBase , Object[] ) +139
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +229
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +90
   System.Web.Mvc.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12() +80
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation) +453
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation) +453
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation) +453
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation) +453
   System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName) +574`

**Comment by Eldblom** [comment]
This is due to a [bug in Unicorn.](https://github.com/kamsar/Unicorn/pull/191).
The issues is resolved in the assembly in the ["/lib/Unicorn patch"](https://github.com/Sitecore/Habitat/tree/master/lib/Unicorn%20patch) folder. If you are deploying using the standard scripts this assembly should be overwriting the standard Unicorn one - otherwise, please manually copy this to the website /bin folder.
The issue should be fixed in an upcoming release of Unicorn.

**Comment by Eldblom** [comment]
Closed by #ec4faa6
