### ISSUE TITLE
Is the implementation of a static stack in FieldRendererService thread safe?

### ISSUE THREAD

**Issue by markgibbons25** [Sitecore/Habitat#250]
I have a field like this:

```
Html.Sitecore().CurrentItem
        .GetDropLinkSelectedItem(Templates.FooterSocial.Fields.Icon)
        .Field(Templates.Icon.Fields.Class, new {DisableWebEdit = true})
```

Sometimes I'm getting an index out of bounds exception on this line:
`return new HtmlString(endFieldStack.Pop());`

And sometimes getting the InvalidOperationException thrown from 2 lines above. This is found during load testing with multiple threads.

**Comment by Eldblom** [comment]
Thanks good catch
