### ISSUE TITLE
05-Sync-Unicorn issue

### ISSUE THREAD

**Issue by KerimM** [Sitecore/Habitat#251]
When running 05-Sync-Unicorn gulp task, it fails with attached error.
![image](https://cloud.githubusercontent.com/assets/11618862/20966457/a4c252d6-bc7a-11e6-8ce7-4d946abacbeb.png)

I'm using Sitecore 8.2 Update 1 + Web Forms for Marketers 8.2 rev. 160801 NOT SC PACKAGE

![image](https://cloud.githubusercontent.com/assets/11618862/20966689/d16ae162-bc7b-11e6-8c4d-b3e38c60bae1.png)

with default config

what am i doing wrong?

thanks in advance

**Comment by adwooley** [comment]
Actually running in the same problem here, but might be a bit unrelated. My installation is very similar (if not the same) to the configuration Kerim describes above. My "05-Sync-Unicorn" always errors out when it gets to the Web Forms section.  Can anybody relate experiences with this?

**Comment by Eldblom** [comment]
Sorry, we havent tested with 8.2.1 yet. 
@kamsar any known Unicorn issues with 8.2.1?

**Comment by kamsar** [comment]
No but I haven't tested that thoroughly. What I've done so far has been
fine. Including calling the sync API from powershell.

The error seems to be coming from a misbehaving non-unicorn event handler
though. I'd be surprised if it was a Unicorn specific issue.

**Comment by adwooley** [comment]
Wow - you sure both come back with support in a quick way! Much appreciated. For more information, here is what I am looking at when trying to sync the "Project.Habitat.Website" from within Unicorn.aspx:   
![habitaterror](https://cloud.githubusercontent.com/assets/4239259/20996806/ab53a73e-bd43-11e6-8b92-a6e21e909e18.JPG)

I've been at this for a day now, but can't seem to find any resolution.  (I would like to dive into the architecture of Habitat, so if you know a sure-fire way of getting an environment going, would appreciate it.  Perhaps a Sitecore different version? Any advice would be appreciated)

**Comment by yassinealahyane** [comment]
Did you take the good zip package for WFFM?
Kerim said he took the NOT SC Package.
You actually have to unzip this one and you the inner zip package to install WFFM...

Regards,

Yassine

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Dec 7, 2016 at 10:43 PM -0500, "adwooley" <notifications@github.com<mailto:notifications@github.com>> wrote:


Wow - you sure both come back with support in a quick way! Much appreciated. For more information, here is what I am looking at when trying to sync the "Project.Habitat.Website" from within Unicorn.aspx:
[habitaterror]<https://cloud.githubusercontent.com/assets/4239259/20996806/ab53a73e-bd43-11e6-8b92-a6e21e909e18.JPG>

I've been at this for a day now, but can't seem to find any resolution. (I would like to dive into the architecture of Habitat, so if you know a sure-fire way of getting an environment going, would appreciate it. Perhaps a Sitecore different version? Any advice would be appreciated)

-

**Comment by adwooley** [comment]
Yassine, thanks for joining in. What I'm using is "Web Forms for Marketers 8.2 rev. 160801 NOT SC PACKAGE.zip".  

Inside of this there are two zips:
-  Web Forms for Marketers 8.2 rev. 160801.zip
-  Web Forms for Marketers CD 8.2 rev. 160801.zip

Am I simply installing the module incorrectly? I was using the parent zip. Should I use just one of the inner zips?

**Comment by kamsar** [comment]
Based on the error, you're trying to deserialize the 'habitat' item and
it's saying the parent item for it (by id) was not found.

It sounds like one way or another WFFM is not installed correctly. Or at
least one of its default items is missing.

**Comment by adwooley** [comment]
Thanks Kamsar. That's really the only conclusion that I can come up with. Being a newbie, can you advise which module package (zip package) would yield best results?  As mentioned above, I am using "Web Forms for Marketers 8.2 rev. 160801 NOT SC PACKAGE.zip".   I'm using the SIM 1.4 "install modules" feature from the context menu?  That all sound good?

**Comment by kamsar** [comment]
I'd unzip the NOT SC PACKAGE and install the package within via the
sitecore desktop. I've had bad luck with silent (e.g. Sim) installs of WFFM
myself.

**Comment by adwooley** [comment]
Thanks again, Kamsar.  Two zips included in NOT SC PACKAGE.  Install both, I assume. Will try your suggestion and will revert tomorrow.

**Comment by sc-simardeepsingh** [comment]
Just Install the **Web Forms for Marketers 8.2 rev. 160801.zip** , other zip is for Content Delivery use.
Hopefully it will help.

**Comment by Eldblom** [comment]
I would recommend not using SIM for the module packages - it does not work well with most. Also, make sure you download and install the latest version for 8.2.1.
There is also an installation guide which describes it all.
https://dev.sitecore.net/Downloads/Web_Forms_For_Marketers/82/Web_Forms_For_Marketers_82_Update1.aspx

**Comment by adwooley** [comment]
To all who contributed, I'd like to report my results. Success! (with one error at the end)
As per everyone's advice, I did a clean installation and used **Web Forms for Marketers 8.2 rev. 160801.zip**.  Then I ran the **default** script in the VS Task Runner Explorer. Everything went through except for that pictured here.  So, Habitat is up and running. Now... time to study.  I must say one thing - the community support for Sitecore is definitely top notch. Thanks to everybody. 
![habitaterror](https://cloud.githubusercontent.com/assets/4239259/21036031/81b44e2e-be06-11e6-82a5-b25e1937f4a4.JPG)

**Comment by KerimM** [comment]
i made a new instance using Sitecore 8.2 initial release and success!
Maybe the new version is bugged.
thanks for the help

**Comment by suryagahlot** [comment]
I created a new instance using Sitecore 8.2 rev. 160729.zip and installed Web Forms for Marketers 8.2 rev. 160801.zip module from sitecore desktop but still getting this error when I run default task.

![image](https://cloud.githubusercontent.com/assets/11260597/21096301/65df94fc-c085-11e6-842e-df0a8beb6839.png)

Please help!

Thanks 
Surya

**Comment by PolingtonAlphonse** [comment]
Hi, 
   I created clean new instance using sitecore 8.2 Initial version and installed Web Forms for Marketers 8.2 rev. 160801 NOT SC PACKAGE.zip module from Sitecore desktop. But still getting following error when I run default task. 

http://www.screencast.com/t/23m9CreA

Any Idea to resolve this issue?

**Comment by Eldblom** [comment]
As the name indicates, the "Web Forms for Marketers 8.2 rev. 160801 NOT SC PACKAGE.zip" is not a sitecore package and therefore cannot be installed. You need to manually unzip the file and install the "Web Forms for Marketers 8.2 rev. 160801.zip" package inside the NOT SC PACKAGE file.

There is an installation guide which describes it all:
https://dev.sitecore.net/Downloads/Web_Forms_For_Marketers/82/Web_Forms_For_Marketers_82_Update1.aspx

**Comment by suryagahlot** [comment]
Finally installation is successful with Sitecore 8.2 rev. 160729.zip & Web Forms for Marketers 8.2 rev. 160801.zip.
Mistake : I was ignoring **post installation steps** for Web Forms for Marketers 
Thanks guys

**Comment by PolingtonAlphonse** [comment]
Eldblom, 

         Thank you for your response.  The installation is successful after installing "Web Forms for Marketers 8.2 rev. 160801.zip" package inside the NOT SC PACKAGE file. . However, the gulp default task was not responding at the '05-Sync-Unicorn'... task. However I got another workaround for this., I could synchronize items through unicorn.aspx. It's working fine now. 

Thanks, 
Polington

**Comment by AccuType-911** [comment]
I also had issue that the task 05-Sync-Unicorn couldn't finish. What I've done is to sync it manually on /unicorn.aspx page.

**Comment by tarek294** [comment]
After many trials with habitat i learned these points:

1. Install only compatible packages
2. Backup bin folders to restore if you overwrite dlls with non compatible packages.
3. Some packages like Web Forms for Marketers is not a sitecore package ( NOT SC PACKAG), You have to extract this file and then use the .zip files inside this as sitecore installation packages. 
This point solve sync solve error for me.
4. Some package like Email Experience Manage need manual configuration (attach database, add connection strings,...)
https://blog.horizontalintegration.com/2017/04/02/sitecore-email-experience-manager-installation-configuration/
5. If we face any browser check installation and configuration of mangodb.
6. We need to check compatibility version of build Visual Studio 2017 doesn't install Build Tools 15.0 by default
https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017
