### ISSUE TITLE
Rebuild analytics index - Sitecore.Data.Database. No matching constructor was found.

### ISSUE THREAD

**Issue by Sivalingaamorthy** [Sitecore/Habitat#254]
I am struck with the below error, what is wrong? can someone throw some light / thoughts please.

> Server Error in '/' Application.
> 
> Could not create instance of type: Sitecore.Data.Database. No matching constructor was found.
> 
> Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 
> 
> Exception Details: Sitecore.Exceptions.ConfigurationException: Could not create instance of type: Sitecore.Data.Database. No matching constructor was found.
> 
> Source Error: 
> > 
> Line 103:    public Job StartRebuildAnalyticsIndexJob()
> Line 104:    {
_**> Line 105:      var options = new Sitecore.Jobs.JobOptions("Rebuild analytics index", "Indexing job", "shell", this, "RebuildAnalyticsIndex");
> Line 106:      return Sitecore.Jobs.JobManager.Start(options);**_
> Line 107:    }
> 
> Source File: E:\Sitecore\Habitat-master\Habitat-master\src\foundation\Installer\code\MongoRestore\MongoRestoreService.cs    Line: 105 
> 
> Stack Trace: 
> 
> 
> [ConfigurationException: Could not create instance of type: Sitecore.Data.Database. No matching constructor was found.]

**Comment by sergeyshushlyapin** [comment]
It seems you're running Sc 8.2, so that the database type should be `Sitecore.Data.DefaultDatabase`. Check your configuration.

**Comment by Sivalingaamorthy** [comment]
I am running habitat in Sc 8.1, do i need to consider anything else ?

**Comment by yassinealahyane** [comment]
Yes, you need to clone the tagged version of habitat that runs under 8.1, which I think is release 1.1

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Dec 14, 2016 at 10:10 AM -0500, "Sivalingaamorthy" <notifications@github.com<mailto:notifications@github.com>> wrote:


I am running habitat in Sc 8.1, do i need to consider anything else ?

-
