### ISSUE TITLE
05-Sync-Unicorn Gulp task raises exception

### ISSUE THREAD

**Issue by krimos** [Sitecore/Habitat#258]
Hi guys, 

I am trying to install Habitat. When it comes to run the Default Gulp Tasks. 
05-Synch-Unicorn Task hang on, in sitecore Log files I found a lot of this exception :

Message: Could not instantiate event handler. Type: Sitecore.ContentSearch.Events.PackagingEventHandler. Method: OnPackageInstallStartingRemoteHandler (method: Sitecore.Events.Event.GetConfigSubscribers()).
Source: Sitecore.Events.Event.GetConfigSubscribers()
   à Sitecore.Diagnostics.Error.Raise(String error, String method)
   à Sitecore.Events.Event.EventSubscribers.Add(String eventName, XmlNode configNode)
   à Sitecore.Events.Event.GetConfigSubscribers()
   à Sitecore.Events.Event.RaiseEvent(String eventName, Object[] parameters)
   à Sitecore.ContentSearch.Maintenance.IndexDatabasePropertyStore.Get(String key)
   à Sitecore.ContentSearch.LuceneProvider.LuceneIndexSummary.get_LastUpdatedTimestamp()
   à Sitecore.ContentSearch.Maintenance.Strategies.BaseAsynchronousStrategy.ReadQueue(EventQueue eventQueue)
   à Sitecore.ContentSearch.Maintenance.Strategies.BaseAsynchronousStrategy.Run()
   à Sitecore.ContentSearch.Maintenance.Strategies.IntervalAsynchronousStrategy.Run()
   à Sitecore.ContentSearch.Maintenance.OperationMonitor.ExecuteActions(ConcurrentQueue`1 actions, String groupName)

I installed Sitecore 8.2 Update 1 Using SIM, then Using Sitecore Package for Webform for Marketers 8.2 rev.161129.

Any of you had this issue before ? Thanks.

**Comment by Eldblom** [comment]
Habitat is still on Sitecore 8.2 initial release. We are still testing on update 1.

**Comment by krimos** [comment]
Thank you Thomas for the quick answer. 
Don't hesitate, if you can give me some insights so I will debug it in my side.

**Comment by paurban** [comment]
I have exacly the same issue with 8.2 Initial Release

**Comment by yassinealahyane** [comment]
Whcih version of WFFM are you using?

**Comment by paurban** [comment]
@yassinealahyane Web Forms for Marketers 8.2.rev. 160801

**Comment by yassinealahyane** [comment]
This is weird, because OnPackageInstallStartingRemoteHandler is new with 8.2.1.
When you go to http://[YourSitecoreInstance]/Sitecore/admin/showconfig.aspx and search for 'OnPackageInstallStartingRemoteHandler' Do you find any result in there?
If yes it means you're somehow using 8.2.1 either in your SItecore Installation or your references.
Can you also go to [YourSitecoreInstanceFolder]/Website/bin, right-click on Sitecore.ContentSearch.dll? and telle me which version you have?

Thanks.

**Comment by paurban** [comment]
Finally we (@paurban and @krimos ) found the issue with Unicorn Synchronisation.  We had an old version of Powershell - 2.0 (same ghost image).  We just had to install newer version ( 4.0)
Could not load file or assembly file MicroCHAP.dll or one of its dependencies. THis assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded.

**Comment by krimos** [comment]
I confirm, I installed Windows Management Framework 5 and all is working fine now. 
Thank you guys.
