### ISSUE TITLE
Gulp ms-build task not running? 

### ISSUE THREAD

**Issue by alinulms** [Sitecore/Habitat#26]
At some point after forking the project and working on it any of the publishing tasks seem to not work. For some reason the gulp-msbuild package is not working. 

Does it happen only for me? 

I have tried to do this as Thomas advised:
Open package.json and remove the ^ in front of msbuild: 0.2.13

but that didn't help.

**Comment by dashkodo** [comment]
After setting strict version of msbuild please remove "node_modules" folder and restore packages

**Comment by alinulms** [comment]
What you mean is remove the node_modules folder then run a npm install? 

I have tried that several times but with no luck. I'll give it a go one more time but i'm sure that's not it.

**Comment by dashkodo** [comment]
Actually yes, remove and run "npm install"

**Comment by alinulms** [comment]
does not help ... however when i run npm install i get just at the start this error... which i'm not sure i am supposed to get although is not related to msbuild module

![image](https://cloud.githubusercontent.com/assets/4048118/11337712/5175fee0-91ef-11e5-99de-ed216832511e.png)

**Comment by dashkodo** [comment]
We have same issue with "addRemoteGit" message on CI server, but it does not affect build pipeline.

**Comment by alinulms** [comment]
Ok found the fix: remove the ^ in front of msbuild: 0.2.13 delete the node_modules folder and then run the npm install.

**Comment by alinulms** [comment]
Solved the issue. Install latest node, remove and reinstall node packages. In the gulpfile.js i've set  logCommand: false,
verbosity: "minimal",

and now everything seems to be working fine.
