### ISSUE TITLE
How to apply different Theme to different websites

### ISSUE THREAD

**Issue by Sivalingaamorthy** [Sitecore/Habitat#261]
I find Habitat more interesting, just trying to figure out, how I can apply different theme to the different sites, in this Habitat example we have one theme (Foundation.Theming.config).

Can someone suggest on this, appreciate your valuable inputs?

**Comment by Eldblom** [comment]
Check out the feature/ThemedAssets branch. This will allow assets to be assigned on rendering level, config level, and site level. Furthermore it allows assets to be assembled on item - Themes - which can then be assigned to a site root.
Also integrated PR#252 and fixes issue #203 
Will be merged into master soon.
