### ISSUE TITLE
Refferenced assemblies should be copy local : false

### ISSUE THREAD

**Issue by alinulms** [Sitecore/Habitat#27]
Hi,

I have forked the project and when i run the Publish from the Task runner i get build errors even if i do a VS normal build i do not get them. I tracked the issue down to be that the Sitecore or Project assemblies that are copied locally on build. 

Of all projects Accounts and Search were building ok. The rest were failing. Once i switched the copy local to false on Sitecore.Kernel.dll and Sitecore extensions dll then they start to build correct. 

I think copy local false should be set on these referenced dll whenever they are added. 

This is more of a possible debate issue than an error considering nobody else has complained about it

**Comment by dashkodo** [comment]
Please attach build log.

**Comment by steviemcg** [comment]
Hey Alin,

Generally I find this disables Intellisense in several areas.

In other projects I work around it by leaving Copy local as true but then skipping it in the publishing profile :-/

**Comment by alinulms** [comment]
Is true Steve,

but does the publishing using the task viewer work? 

i get all sort of errors like this:

![image](https://cloud.githubusercontent.com/assets/4048118/11338331/b98f6b5c-91f3-11e5-8c5d-11403353d3dd.png)


But i'm with you on this one.. intellisense does not work and it is a nightmare. What is the workaround then?

**Comment by dashkodo** [comment]
Could you set properties for gulp-msbuild:
```
{
  logCommand: true, 
  verbosity: "normal"
}
```
could you set it in 46 row of gulpfile.js

**Comment by alinulms** [comment]
You have it here :
![image](https://cloud.githubusercontent.com/assets/4048118/11338454/7a3655a0-91f4-11e5-95e0-340096956b95.png)

**Comment by GoranHalvarsson** [comment]
And it's VS2015 you are using, yes?

**Comment by alinulms** [comment]
Yes

**Comment by dashkodo** [comment]
Actually I'm agree that all references except nuget pkg based should be set to false, but it is not critical for us right now

**Comment by alinulms** [comment]
Then how can i run the task for publishing all the projects?

And setting it to false will disable intellisense in some cases... 

Can you guys run the Publish task with no problems?

**Comment by GoranHalvarsson** [comment]
Yes it works for me, sometimes the taskrunner can't see the tasks(When I have added a new project) Then a restart of the VS is needed.

Could your stuff be OS related? I still run on windows 8.1

**Comment by dashkodo** [comment]
Intellisense shouldn't be a build stopper for msbuild, it is VS feature

**Comment by alinulms** [comment]
Intellisense is not a build stopper. But if i set copy local false to the dll's then builder works but intellisense doesn't. So it seems this is an issue only on my machine as for others it works. And it did work on my machine too.

Considering i have made a clean fork and setup the project from scratch i think the problem is not with the project. I will try to figure out what the issue is and let you guys know.

**Comment by alinulms** [comment]
nobody is up for a live debug of this issue?

**Comment by alinulms** [comment]
I managed to do a workarround. Publishing from Task Runner is still faulty but i can build my solution normally and then deploy views and dll's. For now this may work.
