### ISSUE TITLE
Can't place the same dynamic placeholder at same level

### ISSUE THREAD

**Issue by kmartindale** [Sitecore/Habitat#272]
If I want to create a dynamic placeholder structure like this:

- grid
-       grid-row
-          col-10
-       grid-row
-          col-2

I seem to be unable. It places both col-10 and col-2 in the first instance of the grid row. I thought dynamic placeholders would take care of this issue? Please advise, thanks!

**Comment by Eldblom** [comment]
This seems more like a question for the DynamicPlaceholders implementation: https://github.com/Fortis-Collection/dynamic-placeholders-mvc
