### ISSUE TITLE
Gulp Nuget Restore Do Not Use the Right MsBuild

### ISSUE THREAD

**Issue by jflheureux** [Sitecore/Habitat#273]
It is probably due to my employer development environment setup but the gulp Nuget restore task is using MsBuild 3.5 instead of 4 by default. This makes the step to fail, being unable to access the Habitat solution file.

I succeded to force MsBuild 4 by passing additional parameters to the gulp-nuget-restore task. Pull request incoming.

**Comment by Eldblom** [comment]
Sorry about the delay.
You should consider the PATH environment variable as nuget.exe seems to automatically pick from this. https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference
