### ISSUE TITLE
Issue with Sitecore 8.1.160519

### ISSUE THREAD

**Issue by alokce** [Sitecore/Habitat#276]
Hi,

I am using the Habitat repository and when run the default task in the Visual Studio Task Runner Explorer it get stuck at task '05-Sync-Unicorn'. It always shows Starting '05-Sync-Unicorn' and never completed. Where do you log the error / exception so that I can check if any error occurred during this task. All other tasks are completed successfully.

Thanks,
Alok...

**Comment by scottmulligan** [comment]
If you have successfully setup the main 3 config files for Habitat then it should be pointing to the base Sitecore installation that you have setup. The best place to start is by reviewing the standard Sitecore log files that are created in the "/data/logs" directory of your Sitecore site. The '05-Sync-Unicorn' step will attempt to start adding items to your site and will log this with lines starting with "Unicorn". Please review the latest log file starting with "log.*" and see if there are any helpful clues that point us in the right direction. good luck!

**Comment by scottmulligan** [comment]
Oh, it is also important to use the exact version of Sitecore referenced in the setup instructions for Habitat. Please use Sitecore 8.2 update 1 which is the current supported version. If you use other versions then you might run into issues with the NuGet refences.
