### ISSUE TITLE
Publishing issue

### ISSUE THREAD

**Issue by alokce** [Sitecore/Habitat#277]
Hi Team,

I am using the Habitat repository and when run the default task in the Visual Studio Task Runner Explorer it throws the following error.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Deploy\Microsoft.Web.Publishing.Deploy.FileSystem.targets(96,5): error : Copying file obj\Debug\Package\PackageTmp\packages.config to C:\inetpub\wwwroot\mysitename\Website\packages.config failed. The process cannot access the file 'C:\inetpub\wwwroot\mysitename\Website\packages.config' because it is being used by another process. [D:\myprojectfolder\src\foundation\Indexing\code\Sitecore.Foundation.Indexing.csproj]

Due to this files are not getting published and leave the site in unstable state. Some time it don't throw any exception and run all tasks smoothly. But several times (9 times out of 10 attempts) it fails. 

Please let me know if have resolved this issue.

Thanks,
Alok...

**Comment by Eldblom** [comment]
See issue #281
