### ISSUE TITLE
05-Sync-Unicorn fails to complete on new installation

### ISSUE THREAD

**Issue by rroman81** [Sitecore/Habitat#278]
I have a clean install of SiteCore 8.2 Update 1 with Webforms for Marketers module installed. Upon first build of the solution, the gulp task fails on '05-Sync-Unicorn' with this error:

Info: [A] 
Error: master:/sitecore/system/Modules/Web Forms for Marketers/Settings/Actions/Save 
Error: Actions/Register an Outcome (90538392-5648-4326-b506-e1913ed1daa8) Info: [A] 
Error: master:/sitecore/layout/Renderings/Modules/Web Forms for Marketers/Mvc Form 
Error: (f2cca16d-7524-4e99-8ee0-78ff6394a3b3) Info: [A] 
Error: master:/sitecore/system/Modules/Web Forms for Marketers/Settings/Actions/Save 
Error: Actions/Register an Outcome (90538392-5648-4326-b506-e1913ed1daa8) Info: [A] 
Error: master:/sitecore/layout/Renderings/Modules/Web Forms for Marketers/Mvc Form 
Error: (f2cca16d-7524-4e99-8ee0-78ff6394a3b3) Error: 2 errors occurred during 
Error: deserialization. Earlier log messages for items below should be ignored; an 
Error: error occurred that was retried and failed to 
Error: correct.master:/sitecore/system/Modules/Web Forms for 
Error: Marketers/Settings/Actions/Save Actions/Register an Outcome (90538392-5648-4326
Error: -b506-e1913ed1daa8)C:\Users\roma\proj\Habitat\src\Foundation\forms\serializatio
Error: n\Foundation.Forms.WffmActions.RegisterOutcome\Register an Outcome.yml> 
Error: ParentItemNotFoundException: Exception of type 
Error: 'Sitecore.Data.Serialization.Exceptions.ParentItemNotFoundException' was 
Error: thrown.master:/sitecore/layout/Renderings/Modules/Web Forms for Marketers/Mvc 
Error: Form (f2cca16d-7524-4e99-8ee0-78ff6394a3b3)C:\Users\roma\proj\Habitat\src\Found
Error: ation\forms\serialization\Foundation.Forms.Renderings.MvcForm\Mvc Form.yml> 
Error: ParentItemNotFoundException: Exception of type 
Error: 'Sitecore.Data.Serialization.Exceptions.ParentItemNotFoundException' was 
Error: thrown.
Error: For full stack traces of each exception, see the Sitecore logs. Info: Info: 
Error: Completed.
Error: At C:\Users\roma\proj\Habitat\scripts\Unicorn\Unicorn.psm1:43 char:12
Error: +     $result = Invoke-WebRequest -Uri $url -Headers @{ "X-MC-MAC" = 
Error: $signature; "X-M ...
Error: +    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: ~~~~~~
Error:     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt 
Error:    pWebRequest) [Invoke-WebRequest], WebException
Error:     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe 
Error:    ll.Commands.InvokeWebRequestCommand

This is most likely related to [issue 211](https://github.com/Sitecore/Habitat/issues/211)

**Comment by snehithvelma** [comment]
I struggled with this issue for a day and found that by adding the MicroChap dll version "1.2.1.0" instead of "1.2.2.0" fixed my issue.

**Comment by smolinacadena** [comment]
How do I perform this change for the MicroChap dll?

**Comment by rroman81** [comment]
@snehithvelma , i am interested to know that as well

**Comment by snehithvelma** [comment]
The powershell script which is run by the Gulp Task Sync-Unicorn references the microchap dll which should be somewhere in your local file explorer.
So if you get the older version of microchap dll (From Nuget or Unicorn repo) and replace it in the folder where your script references, then it should work.

**Comment by a2wd** [comment]
Just want to confirm this solves the issue here too

**Comment by AUpalekar** [comment]
I faced the same issue and I was trying for the solution mentioned above. But then I thought such basic dll issues should not happen . This issue is happening as WFFM module is failed to install successfully. You retry installing the WFFM module and confirm. I solved this issue by taking fresh instance Sitecore 8.2 update 1 and installed  WFFM 8.2 update 1 immediately. Then I followed remaining steps and everything worked fine.

**Comment by MikeIsHereWorking** [comment]
Just replaced 1.2.2.1 with 1.2.1.0 and I get the same error 

2 errors occurred during deserialization. Earlier log messages for items below should be ignored; an error occurred that was retried and failed to correct.
master:/sitecore/system/Modules/Web Forms for Marketers/Settings/Actions/Save Actions/Register an Outcome (90538392-5648-4326-b506-e1913ed1daa8)
C:\projects\Habitat\src\Foundation\Forms\serialization\WffmActions.RegisterOutcome\Register an Outcome.yml
> ParentItemNotFoundException: Exception of type 'Sitecore.Data.Serialization.Exceptions.ParentItemNotFoundException' was thrown.
master:/sitecore/layout/Renderings/Modules/Web Forms for Marketers/Mvc Form (f2cca16d-7524-4e99-8ee0-78ff6394a3b3)
C:\projects\Habitat\src\Foundation\Forms\serialization\Renderings.MvcForm\Mvc Form.yml
> ParentItemNotFoundException: Exception of type 'Sitecore.Data.Serialization.Exceptions.ParentItemNotFoundException' was thrown.

For full stack traces of each exception, see the Sitecore logs.

**Comment by manishramanan15** [comment]
Facing similar issue unable. Tried with older versions of MicroCHAP dll doesnt work. Authentication fails with older versions. With new version fails while trying to sync Web Forms for Marketers/Mvc Form

**Comment by koga73** [comment]
Same issue. @MikeIsHereWorking did you resolve this?

**Comment by manishramanan15** [comment]
It was a mistake from my end.
I was on master branch. Switched to release and appropiate Installed version and tried the steps again and it worked.
Also make sure you have covered the two prerequisite steps  mentioned in Step 3 here https://github.com/Sitecore/Habitat/wiki/01-Getting-Started

Hopefully it will helps you @koga73.
