### ISSUE TITLE
'05-Sync-Unicorn' error. TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by hfishere** [Sitecore/Habitat#284]
![capture](https://cloud.githubusercontent.com/assets/13634344/23640178/93cefe08-031e-11e7-9842-dd81fa6b4581.PNG)

I run 'default' from gulpfile at Task Runner Explorer in VS but always fail at Task 5 (Sync-Unicorn). 
But sync is worked if using unicorn.aspx, am i doing something wrong or maybe not properly at unicorn config?

**Comment by Eldblom** [comment]
Please check your configuration. The unicorn script reads a shared secret from `config.websiteRoot` + "/App_config/Include/Unicorn/Unicorn.UI.config";`. If this file is not found or does not contains a valid SharedSecret the script will fail.

**Comment by hfishere** [comment]
Thanks @Eldblom

**Comment by mjv21** [comment]
@Eldblom Which configuration?  I have the same error but I'm not sure where I would change this?
