### ISSUE TITLE
05 - Sync-unicorn fails with 'Could not load type 'Sitecore.ContentSearch.IIndexOperationsEx'

### ISSUE THREAD

**Issue by LeannSMU** [Sitecore/Habitat#288]
Just reviewed issue https://github.com/Sitecore/Habitat/issues/269 and tried the resolutions mentioned and this did not resolve the Sitecore.ContentSearch.IIndexOperationsEX issue.

Any advice, thanks! 

![2017-03-22_9-29-11](https://cloud.githubusercontent.com/assets/26602150/24202853/140551de-0ee2-11e7-8fa8-a0e14e03e9f9.jpg)

**Comment by Eldblom** [comment]
You are most likely running the wrong version of Sitecore. Please check the [documentation](https://github.com/Sitecore/Habitat/wiki).

**Comment by LeannSMU** [comment]
The documentation directs me to https://dev.sitecore.net/Downloads/Sitecore_Experience_Platform/82/Sitecore_Experience_Platform_82_Update1.aspx which is the version that I have installed (sc82rev161221), Is this not the correct version? Thank you.
