### ISSUE TITLE
05-Sync-Unicorn Error:

### ISSUE THREAD

**Issue by mjv21** [Sitecore/Habitat#299]
![image](https://cloud.githubusercontent.com/assets/9357701/24611421/0cf08dce-1850-11e7-87fb-b9573313d445.png)

Im trying to finish the installation of the demo project and am running into this issue on step 5 of the default task.  Has anyone seen this before?  I can't seem to figure out why its doing this.

**Comment by codingdennis** [comment]
Hello mjv21, it might be easier if you could provide a dump of the whole output as the screenshot above is a generic error and usually if you scroll up from the output window you will almost find what went wrong.

**Comment by Eldblom** [comment]
@mjv21 Whenever you get issues with unicorn in the console go and run http://mysite/unicorn.aspx?verb=Sync. This will run a full sync and provide much better output.
