### ISSUE TITLE
Content editor broken after install Habitat

### ISSUE THREAD

**Issue by eyegates** [Sitecore/Habitat#300]
I've just installed Habitat on my local following the official guide lines. once the code published and unicorn synced with my sitecore instance, I can't make the content editor work and I get javascript errors everytime I select an Item in the content tree.

![image](https://cloud.githubusercontent.com/assets/11899589/24662452/5e99257c-1955-11e7-8cbc-7fa5b9025abc.png)

Someone can help?
Thanks

**Comment by jameshirka** [comment]
Can you confirm what version of Sitecore and what version of WFFM you have installed?
I had a similar issue when I was using the wrong version of WFFM.

**Comment by eyegates** [comment]
Thanks for your answers

I'm using Web Forms for Marketers 8.2 rev. 161129 and
Sitecore 8.2 rev. 161115

I've tried Sitecore 8.2 rev. 160729 too and get the same result

Thanks

**Comment by Eldblom** [comment]
No feedback, closing
