### ISSUE TITLE
Incorrect reference of Sitecore.Feature.Media in Sitecore.Foundation.Indexing.Tests project

### ISSUE THREAD

**Issue by agehlot** [Sitecore/Habitat#303]
Hi Team,

There is a reference of Feature layer in Foundation layer which should not be there based on Helix principle. I think, somebody by mistaken add reference of Sitecore.Feature.Media in Sitecore.Foundation.Indexing.Tests project.

If my understanding is correct and this reference should be removed from Sitecore.Foundation.Indexing.Tests, please remove this reference and commit the code.

Thanks,
Arvind Gehlot

**Comment by Eldblom** [comment]
Thanks. You are correct - fixed and will be committed soon.

**Comment by jflsitecore** [comment]
Fixed by #308
