### ISSUE TITLE
DynamicPlaceholders.dll and DynamicPlaceholders.Mvc.dll missing when using gulpfile-ci.js "CI-Publish" task

### ISSUE THREAD

**Issue by rolek** [Sitecore/Habitat#309]
When using the "gulpfile-ci.js" and the CI-Publish task, some Dlls are missing in the output bin directory.
DynamicPlaceholders.dll and DynamicPlaceholders.Mvc.dll for sure.

There probably will be others missing, depending on number of nuget packages added and other references.

**Comment by nickwesselman** [comment]
No longer applicable.
