### ISSUE TITLE
Feature.Search > "Results on page" setting is ignored

### ISSUE THREAD

**Issue by demaev** [Sitecore/Habitat#314]
Page size defined in rendering parameters of the Paged Search Results rendering is ignored and default one defined in Sitecore.Feature.Search.Models.PagingSettings.cs is always used. 
![image](https://cloud.githubusercontent.com/assets/18694521/25600399/4db20e94-2f27-11e7-9a39-55f02c48c100.png)

**Comment by Eldblom** [comment]
Thanks for finding that. The latest update introduces multiple renderings which triggers the actual search - specifically the header, facets and search results. All of these renderings needs the rendering parameters and you should set the page size on the first rendering in the list.
This will be fixed asap.
