### ISSUE TITLE
Suggestion: Site specific pipeline processors

### ISSUE THREAD

**Issue by yiangos** [Sitecore/Habitat#325]
In the following John West article https://community.sitecore.net/technical_blogs/b/sitecorejohn_blog/posts/site-specific-pipeline-processors-in-the-sitecore-asp-net-cms

he describes a solution to a very common issue when dealing with multisite installations: We don't want to have item resolvers of Site A run when the current request is for Site B and vice versa. The reason is simply that we are adding more processors than we actually need. 

I've already used this particular solution in sites that are currently in production with 100% success, and I've seen performance gains that were non-negligible.

I feel it should be in there. If you feel the same, please let me know so that I make the relevant fork and pull request.

Regards,
Yiannis

**Comment by nickwesselman** [comment]
Hi @yiangos -- Same here, trying to reduce platform extensions in Habitat. I'd welcome a Helix PR once again here.
https://github.com/Sitecore/Helix.Docs
