### ISSUE TITLE
Suggestion: Switching Link Provider

### ISSUE THREAD

**Issue by yiangos** [Sitecore/Habitat#326]
Sitecore currently offers a single, instance-wide Link Manager.

We've created a solution whereby this is replaced by a "switching" Link Manager, that then looks up in the site definition for a site-specific Link Manager type, and creates an instance of that type with reflection, with a fallback scenario of using the stock Sitecore Link Manager.

The reasoning behind this is that if we have a multisite solution where each site introduces its own quirks about item resolution and link creation (e.g. each site has a bucket of items with different means of resolution and linking) then we either have to break Helix principles by introducing implicit dependencies between the two sites within the same single (custom) Link Manager implementation, or we break Helix principles by moving the Link Manager implementation to the Foundation Layer, thus introducing a Feature (or Project) dependency in the Foundation Layer.

This solution has the "Switching Link Provider" in the Foundation/Multisite module, which is agnostic of the specifics of each site link management requirements. The specifics are implemented in each site's specific Link Manager implementation (e.g. as a Feature Layer module, one for each Manager required) and are bound to each site at the Project layer (within each site definition). This maintains the dependency direction properly, and also solves the issue of (multiple site)-(multiple linking requirements)-(single Link Manager).

I believe this should be included in the solution. if you feel the same, please let me know so that I prepare a fork and make a pull request.

Regards
Yiannis

**Comment by nickwesselman** [comment]
Hi @yiangos -- Thanks for the suggestion, however I'm trying to reduce platform extensions in Habitat. It sounds like for your specific requirements, this is an appropriate approach, and potentially should be described in Helix docs. I would definitely consider a PR on the Helix docs describing this.

https://github.com/Sitecore/Helix.Docs
