### ISSUE TITLE
SC82u3 unable to make the first Sync with unicorn

### ISSUE THREAD

**Issue by danteciambella** [Sitecore/Habitat#332]
Hi guys we are using Sitecore 82u3 and we have problems with the first Unicorn Sync from VS to Sitecore instance. The **05-Sync-Unicorn** tell me that I need to do the first Sync. When I try to use **http://<instance>/unicorn.aspx** the page tell me that there are a lot of miss configuration and I can't do the first sync. How can I avoid this issue?
Is the problem related with the Sitecore version?

Dante.
Regards.

**Comment by TonyMilton** [comment]
Have you tried syncing Foundation.Theming first and then the others after on the Unicorn.aspx page?  After this I've found 05-Sync-Unicorn to work OK.

**Comment by danteciambella** [comment]
No Tony I can't sync the Foundation.Theming. Seems that the first 05-Sync-Unicorn is not moving items from serialized version to the DB

**Comment by dnstommy** [comment]
Did you use the default location your files? C:\Websites\Habitat.dev.local? Where you able to gulp 03-Publish-All-Projects?

**Comment by danteciambella** [comment]
Thanks to all guys. Yes the problem was a missing configuration like the one you are telling me. In addition we did't install WFFM. Thanks a lot. Dante
