### ISSUE TITLE
Python dependency

### ISSUE THREAD

**Issue by Tragedie-v-JZD** [Sitecore/Habitat#333]
Hello,

Trying installation of Habitat on my local machine according to installation instructions in wiki.

During **npm install** phase in project repo (working with master branch) I getting message about missing Python/Python2 by one of JS dependencies, but python is not mentoned anywhere in instructions.

Is this mandatory now, or I should search for issue somewhere else?

Thx

**Comment by dnstommy** [comment]
What version of node are you using? I remember having issues if I was on the latest and greatest version.  I am on 6.11.1.

**Comment by Tragedie-v-JZD** [comment]
As version was not specified, I used "current" (so, 8.1.x). But must say, that after installation of Python2 (and adding C++ support into Visual Studio because of building of libsass) I am able to build and deploy habitat solution on my local environment ...

**Comment by asmagin** [comment]
The issue is related to `gulp-sass` dependency, as it is using `node-sass@3.13.1`, which causes this error.
