### ISSUE TITLE
npm install doesn't work

### ISSUE THREAD

**Issue by arencambre** [Sitecore/Habitat#340]
**npm install** in the repository's root directory doesn't work. Command prompt output is in [npm install fail.txt](https://github.com/Sitecore/Habitat/files/1201468/npm.install.fail.txt), and the log file is [2017-08-04T19_41_39_624Z-debug.log.txt](https://github.com/Sitecore/Habitat/files/1201534/2017-08-04T19_41_39_624Z-debug.log.txt)

Notable in **npm.install.fail.txt**:
- Line 11: Tries to download something that doesn't exist. Per https://github.com/sass/node-sass/releases/tag/v3.13.1, 51 is the highest release you can get, but it is trying to download 57. Also, 3.13.1 is an old release.
- Line 45: First of a few errors related to Python. It is finally located in line 64, but then lines 66 and 67 report problems at the same path where it is found in line 64.

**Comment by Eldblom** [comment]
Must be a local problem. Works fine on CI server and locally

**Comment by arencambre** [comment]
This needs to be addressed:

> Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
> Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

That is not "working fine". It is unable to download because the referenced file doesn't exist. Which file did you mean to download?

**Comment by Eldblom** [comment]
My best guess is that it's related to the version of node. Could you try to upgrade or downgrade and try again?

**Comment by arencambre** [comment]
What version of node do you use?

**Comment by arencambre** [comment]
I had 8.2.1 installed. I see that the instructions say "4+".  I switched to 6.11.2 LTS, and that appears to work. I have updated the wiki page.
