### ISSUE TITLE
05 Unicorn Sync throws [MissingMethodException: Method not found: &#39;Void Kamsar.WebConsole.TextWebConsole..ctor(System.Web.HttpResponseBase, Boolean, Boolean)&#39;.]

### ISSUE THREAD

**Issue by davidanewman** [Sitecore/Habitat#342]
I have solved this, just adding it in case anybody else comes across it
However I tried to run the Unicorn task it failed with the following error [MissingMethodException: Method not found: &#39;Void Kamsar.WebConsole.TextWebConsole..ctor(System.Web.HttpResponseBase, Boolean, Boolean)&#39;.] 
Solved it by replacing the Kamsar.WebConsole.dll in the webroot/bin folder with the one from C:\Projects\Habitat\packages\Kamsar.WebConsole.2.0.0\lib\net40 you cannot take any notice of the file date but the version in the webroot was 20.5kb and the replacement is 22kb.

**Comment by Eldblom** [comment]
I think this might stem from the recent upgrade of Unicorn to v4. I recommend blowing away your solution on disk and rebuilding from scratch.

**Comment by lskowronski** [comment]
I resolved that with removing dll file from webroot - to be sure that it will be published again from VS solution.
