### ISSUE TITLE
buildToolsVersion Needs to be Changed as buildToolsVersion: 14.0 for VS 2015

### ISSUE THREAD

**Issue by pradsir** [Sitecore/Habitat#344]
Often times when I run the "Publish-Site" Gulp task I see error codes in red that say MSBuild failed with code 1. 

The Crux here is we need to update gulp-config.js as 

buildToolsVersion: 14.0 for VS 2015

 buildToolsVersion: 15.0 for VS 2017

**Comment by Eldblom** [comment]
This is now a setting which can be set in /gulpconfig.js

**Comment by Eldblom** [comment]
Yes, correct. Please use gulp-config.js to set the right version to fit your VS version.
Habitat is now by default aligned to VS 2017
