### ISSUE TITLE
Getting Error While doing  05-Sync-Unicorn

### ISSUE THREAD

**Issue by pradsir** [Sitecore/Habitat#345]
cmd.exe /c gulp -b "C:\projects\Habitat" --color --gulpfile "C:\projects\Habitat\Gulpfile.js" 05-Sync-Unicorn
Process terminated with code 8.
C:\projects\Habitat\scripts\unicorn.js:44
    if (err !== null) throw err;

I am able to use unicorn.aspx and was able to set up habitat

**Comment by paritoshtripathi** [comment]
I'm getting the same issue as below:

C:\Users\Administrator\Downloads\Habitat-HabitatSynthesis\Habitat-HabitatSynthesis>gulp 05-Sync-Unicorn
[15:39:32] Using gulpfile ~\Downloads\Habitat-HabitatSynthesis\Habitat-HabitatSynthesis\gulpfile.js
[15:39:32] Starting '05-Sync-Unicorn'...
C:\Users\Administrator\Downloads\Habitat-HabitatSynthesis\Habitat-HabitatSynthesis\scripts\unicorn.js:32
    if (err !== null) throw err;
                      ^

Error: Command failed: powershell -executionpolicy unrestricted "./Sync.ps1 -secret kl3KGocnbp3L9ncCZYRPwFwiW7jW2UhE02T3GZU6sL5rTCKZzsRyRYLtGzuh8Li -url http://habitat-synthesis.local/unicorn.aspx"
Invoke-WebRequest :

        The resource cannot be found.


         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;}
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }



            Server Error in '/' Application.
             The resource cannot be found.

             Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable. &nbsp;Please review the
following URL and make sure that it is spelled correctly.

             Requested URL: /unicorn.aspx

            Version Information:&nbsp;Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.2053.0


At C:\Users\Administrator\Downloads\Habitat-HabitatSynthesis\Habitat-HabitatSynthesis\scripts\Unicorn\Unicorn.psm1:56 char:12
+ ...   $result = Invoke-WebRequest -Uri $url -TimeoutSec 360 -UseBasicPars ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)

Any idea??

**Comment by shawdren** [comment]
I have same problem at step 05, but it's different error

> Starting '05-Sync-Unicorn'...
> Error: Invoke-WebRequest : 
> Error:     
>         Could not load file or assembly 'MongoDB.Bson, Version=2.4.4.0, Culture=neutral, PublicKeyToken=null' or one of its
>  dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0
> x80131040)

**Comment by error505** [comment]
Maybe you have same problem as I... I solved it by unblocking MicroCHAP.dll inside scripts/unicorn folder, (right click on the file, click on properties and click on unblock).
Also i changed unicorn.js on line 43 and excluded ExecutionPolicy unrestricted from that line because I had a problem with poweshell security and with this it worked fine.

**Comment by MikeIsHereWorking** [comment]
@error505 link is broken

**Comment by error505** [comment]
@MikeIsHereWorking Link fixed.

**Comment by phaniav** [comment]
We faced an issue where the folder path for Habitat Solution has white space in it 
(e.g E:\\Sitecore Demo\Habitat).

Throws an error message saying 'E:\Sitecore ' is not a valid powershell cmdlet.
We move the solution to different folder without spaces.. trying sync now.
