### ISSUE TITLE
Getting Console Error Post Habitat Installation

### ISSUE THREAD

**Issue by pradsir** [Sitecore/Habitat#346]
Hi 

Post unicorn Sync.

While Navigating in the content tree ; Once I click on given items it's not working.

In a nutshell, content tree is broken

The Error in console says

jsnlog.min.js:1 : {"stack":"Script error. \n at :undefined:undefined","message":"Script error.","logData":"Script error."}
i.cerror @ jsnlog.min.js:1
i.sendLogItemsConsole @ jsnlog.min.js:1
i.sendBatch @ jsnlog.min.js:1
i.log @ jsnlog.min.js:1
n.log @ jsnlog.min.js:1
n.fatalException @ jsnlog.min.js:1
__jsnlog_configure.function.window.onerror @ jsnlog.min.js:1
setTimeout (async)
scContentEditor.onTreeNodeClick @ Content Editor.js:389
scContentEditor.onTreeClick @ Content Editor.js:373
onclick @ Content-Editor?ic=Apps%2F48x48%2FPencil.png&he=Content Editor&cl=0:262
Sitecore.js:1934 XHR finished loading: POST "http://habitat.dev.local/sitecore/shell/Applications/Content-Editor?ic=Apps%2F48x48%2FPencil.png&he=Content%20Editor&cl=0".
scRequest.send @ Sitecore.js:1934
scRequest.execute @ Sitecore.js:1692
scSitecore.postRequest @ Sitecore.js:888
(anonymous) @ Content Editor.js:397
setTimeout (async)
scContentEditor.onTreeNodeClick @ Content Editor.js:389
scContentEditor.onTreeClick @ Content Editor.js:373
onclick @ Content-Editor?ic=Apps%2F48x48%2FPencil.png&he=Content Editor&cl=0:262
VM2426:1 Uncaught TypeError: scContent.updateItemDynamicTabIds is not a function
    at eval (eval at scSitecore.process (Sitecore.js:1043), <anonymous>:1:11)
    at scSitecore.process (Sitecore.js:1043)
    at scRequest.resume (Sitecore.js:1826)
    at scRequest.handle (Sitecore.js:1727)
    at scRequest.execute (Sitecore.js:1695)
    at scSitecore.postRequest (Sitecore.js:888)
    at Content Editor.js:397

**Comment by x3mxray** [comment]
I had the same issue. If you open "Content Editor.js" in browser and in file system - there are 2 different versions. The bug is in caching. Resolved by clearing all application data in:
browser + sitecore/admin/clearcache + restart pool
