### ISSUE TITLE
Missing value for Unicorn config node 'targetDataStore', 'type' attribute (type expected).

### ISSUE THREAD

**Issue by MikeIsHereWorking** [Sitecore/Habitat#352]
I get this error message after running the gulp task in 'default' 
`Missing value for Unicorn config node 'targetDataStore', 'type' attribute (type expected).`
though my unicorn.config looks like 
`<targetDataStore physicalRootPath="$(dataFolder)\Unicorn\$(configurationName)" useDataCache="false" type="Rainbow.Storage.SerializationFileSystemDataStore, Rainbow" singleInstance="true"/>`

I don't know where else to look.

**Comment by javafun** [comment]
How did you manage to solve this problem? I am encountering the same error 

Thanks

**Comment by MikeIsHereWorking** [comment]
We just gave up on Unicorn
