### ISSUE TITLE
SC9 Version

### ISSUE THREAD

**Issue by Roundedcube** [Sitecore/Habitat#359]
I'm almost done with a migration to v9 of the Habitat codebase but there are a few that I still need to figure out how to migrate such as the concept of automation states to the new marketing automation.  Most of the foundation and feature (and of course the project) projects have been migrated including dependency injections, indexing /search(with SOLR),  local datasource, etc.  Also removed items that are now native to v9 like DynamicPlaceholders and those that are deprecated like WFFM (still need to switch it to Experience Forms).  Anyway, I'd like to share it but since it's a whole major version, I don't know how and where.  Anyway, any suggestions from the team would be appreciated.

**Comment by marcotana** [comment]
The Ghost user is me....just had to change to account.

**Comment by jeanfrancoislarente** [comment]
were you aware of the feature/v9 branch that has an open PR?

**Comment by marcotana** [comment]
no i'm not.  i'll check it out.
