### ISSUE TITLE
Update unit tests for feature/v9

### ISSUE THREAD

**Issue by Eldblom** [Sitecore/Habitat#360]
The feature/v9 branch is almost complete, however unit tests was disabled as FakeDb support for v9 was missing when the project started.

Looking for someone to update FakeDb and fix the unit tests.

**Comment by nickwesselman** [comment]
Did a quick spike on this, tasks include:

1. Add `Sitecore.Foundation.Testing` back into solution
1. Update `Sitecore.FakeDb` and `Sitecore.FakeDb.AutoFixture` to 1.7.2.0
1. Update AutoFixture packages to 3.50.3
1. Remove any changes nuget makes to `App.config` (e.g. `System.Runtime` redirect)
1. Remove duplicate AssemblyInfo tags
1. Ensure build
1. Add each unit test project back into the solution, repeat the steps above, ensure build and passing tests

All test projects:
```
Sitecore.Feature.Accounts.Tests.csproj
Sitecore.Feature.Demo.Tests.csproj
Sitecore.Feature.Language.Tests.csproj
Sitecore.Feature.Maps.Tests.csproj
Sitecore.Feature.Media.Tests.csproj
Sitecore.Feature.Multisite.Tests.csproj
Sitecore.Feature.News.Tests.csproj
Sitecore.Feature.Person.Tests.csproj
Sitecore.Feature.Teasers.Tests.csproj
Sitecore.Foundation.Accounts.Tests.csproj
Sitecore.Foundation.Alerts.Tests.csproj
Sitecore.Foundation.Dictionary.Tests.csproj
Sitecore.Foundation.FieldEditor.Tests.csproj
Sitecore.Foundation.Indexing.Tests.csproj
Sitecore.Foundation.Installer.Tests.csproj
Sitecore.Foundation.LocalDatasource.Tests.csproj
Sitecore.Foundation.Multisite.Tests.csproj
Sitecore.Foundation.SitecoreExtensions.Tests.csproj
Sitecore.Foundation.Theming.Tests.csproj
```

**Comment by nickwesselman** [comment]
Unless I'm missing something, looks like unit tests were not updated or created for the refactored Account Foundation and Feature (XConnect), could make this a larger effort than anticipated.

**Comment by nickwesselman** [comment]
Follow-up issues: #392 #393 #394
