### ISSUE TITLE
sync-Unicorn task error on "feature/V9" for Sitecore 9

### ISSUE THREAD

**Issue by faiyazulnoor** [Sitecore/Habitat#363]
I took "feature/V9" code and using Sitecore 9.
sync-Unicorn task giving powershell execution policy restricted issue. My Powershell execution policy is set as ByPass . Also logged in as admin user in VS 2017. "MicroCHAP", "sync", "unicorn" files I have marked them as unblocked .
 
**message in task runner**
`[17:56:26] Starting 'Sync-Unicorn'...
Sync-Unicorn: Executing Sync...
Sync Unicorn
Foundation.Serialization is being synced.
Unable to resolve serialized item for included root path master:/sitecore/system/Settings/Feature. The item does not exist in Serialization File System Data Store. It has been skipped. Perhaps you need to perform an initial serialization from the control panel?
Unable to resolve serialized item for included root path master:/sitecore/system/Settings/Foundation. The item does not exist in Serialization File System Data Store. It has been skipped. Perhaps you need to perform an initial serialization from the control panel?
Unable to resolve serialized item for included root path master:/sitecore/system/Settings/Project. The item does not exist in Serialization File System Data Store. It has been skipped. Perhaps you need to perform an initial serialization from the control panel?
Unable to resolve serialized item for included root path master:/sitecore/system/Settings/Buckets/Facets/Feature. The item does not exist in Serialization File System Data Store. It has been skipped. Perhaps you need to perform an initial serialization from the control panel?
Unable to resolve serialized item for included root path master:/sitecore/system/Settings/Buckets/Facets/Foundation. The item does not exist in Serialization File System Data Store. It has been skipped. Perhaps you need to perform an initial serialization from the control panel?`

**all messages like above only for serialization then error like below**

`****ERROR OCCURRED****
Error: Unicorn Sync to http://sc90xp0.local/unicorn.aspx?verb=Sync&configuration=&skipTransparentConfigs=0 returned an error. 
Error: See the preceding log for details.
Error: At E:\VsSolutions\Habitat-feature-v9\scripts\Unicorn\Unicorn.psm1:66 char:3
Error: +         throw "Unicorn $Verb to $url returned an error. See the prece ...
Error: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error:     + CategoryInfo          : OperationStopped: (Unicorn Sync to...og for details.:String) [], RuntimeException
Error:     + FullyQualifiedErrorId : Unicorn Sync to http://sc90xp0.local/unicorn.aspx?verb=Sync&configuration=&skipTranspare 
Error:    ntConfigs=0 returned an error. See the preceding log for details.
Error:  
E:\VsSolutions\Habitat-feature-v9\scripts\unicorn.js:44
    if (err !== null) throw err;
                      ^
Error: **Command failed: powershell -executionpolicy unrestricted** "E:\VsSolutions\Habitat-feature-v9\scripts/Unicorn/./Sync.ps1 -secret 749CABBC85EAD20CE55E2C6066F1BE375D2115696C8A8B24DB6ED1FD60613086 -url http://sc90xp0.local/unicorn.aspx"
Unicorn Sync to http://sc90xp0.local/unicorn.aspx?verb=Sync&configuration=&skipTransparentConfigs=0 returned an error. 
See the preceding log for details.
At E:\VsSolutions\Habitat-feature-v9\scripts\Unicorn\Unicorn.psm1:66 char:3
+         throw "Unicorn $Verb to $url returned an error. See the prece ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unicorn Sync to...og for details.:String) [], RuntimeException
    + FullyQualifiedErrorId : Unicorn Sync to http://sc90xp0.local/unicorn.aspx?verb=Sync&configuration=&skipTranspare 
   ntConfigs=0 returned an error. See the preceding log for details.
 
    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
Process terminated with code 1.`

**Comment by jeanfrancoislarente** [comment]
I would check your **src\Project\Habitat\code\App_Config\Environment\Project** file.

**Comment by amerbashoeb** [comment]
You need to load https://habitat_xconnect.dev.local/ first and then re-try Sync-Unicorn from Visual Studio.

**Comment by sergeyshushlyapin** [comment]
Is this issue still actual? I've successfully deserialized all the items without any errors from the first attempt...

**Comment by faiyazulnoor** [comment]
It seems to be resolved now. I am able to sync Only change I had to make was to copy paste Sitecore.Marketing.Search dll from vanilla instance to Habitat instance.

**Comment by koga73** [comment]
I'm having this same exact issue with SC9, feature/v9. I tried dropping in Sitecore.Marketing.Search.dll but still getting the same error. Any other suggestions?

**Comment by koga73** [comment]
I got it resolved. I didn't realize that the DevSettings.config file location changed for Habitat v9.

Habitat Sitecore 8 config file:
    /src/Project/Habitat/code/App_Config/Include/Project/z.Habitat.DevSettings.config

Habitat Sitecore 9 config file:
    /src/Project/Habitat/code/App_Config/Environment/Project/Habitat.Dev.config
