### ISSUE TITLE
Problem during installation v9

### ISSUE THREAD

**Issue by SurpriseMoFo** [Sitecore/Habitat#366]
Hi. 
I have this error during the installation. Basically, the database is already locked and the lock is not released. I put the db offline, released the locks, and put it online again. But when I trigger the script again, the same error happens.

![image](https://user-images.githubusercontent.com/35376163/34883897-512be7cc-f7bb-11e7-95e9-5b09d9ccc4b1.png)

![image](https://user-images.githubusercontent.com/35376163/34884564-65b5e60a-f7bd-11e7-8b6a-29e25a74b342.png)

Any ideas? Thanks

**Comment by leduyminh1989** [comment]
Hi, you should remove user of databases Sitecore. And re-install. Exp: marketingautomation database, remove user mảketing, same other databases. Because Sitecore create databases and create different users in databases.

**Comment by SurpriseMoFo** [comment]
Hi. What are the other databases I have to remove users from? Thanks

**Comment by leduyminh1989** [comment]
You can follow this image: https://pasteboard.co/H31eSHE.png
Different users in databases, you have to remove it.
I write English not good. I see a article fix error same me show you (https://chebalt.wordpress.com/2017/11/22/sitecore-9-installation-tips/)

**Comment by SurpriseMoFo** [comment]
But Sitecore is installed correctly. The errors refer to Habitat installation

**Comment by leduyminh1989** [comment]
Hi SurpriseMoFo, I see your screenshot is setup of base Sitecore. Project Habitat only run gulp on base Sitecore.

**Comment by isaadansari** [comment]
Hi @SurpriseMoFo , you can clear the databases and start for the fresh install. The issue usually occurs when the script fails to execute completely and you re run the same script for installation SC9

**Comment by jeanfrancoislarente** [comment]
Is this related to the collectionuser sql user?

**Comment by jeanfrancoislarente** [comment]
@SurpriseMoFo - is this still an issue?

**Comment by faiyazulnoor** [comment]
I have this issue, I can say that when script fails before full installation either you change prefix in parameter section of powershell file or delete all DBs created earlier. If we re run script without doing any one you will face issue .

**Comment by nickwesselman** [comment]
FYI, there is an `uninstall-xp0.ps1` script on the `feature/v9` branch that will clean up anything from a failed / partial install, including the databases.

**Comment by nickwesselman** [comment]
Closing as `uninstall-xp0` can be used for a fresh install when encountering this issue.
