### ISSUE TITLE
Could not load file or assembly 'MongoDB.Bson, Version=1.10.0.62

### ISSUE THREAD

**Issue by zell71** [Sitecore/Habitat#367]
getting this issue when task runner is built and attempts to perform the unicorn sync:

> Could not load file or assembly 'MongoDB.Bson, Version=1.10.0.62, Culture=neutral, PublicKeyToken=f686731cfb9cc103' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
> 
> Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 
> 
> Exception Details: System.IO.FileLoadException: Could not load file or assembly 'MongoDB.Bson, Version=1.10.0.62, Culture=neutral, PublicKeyToken=f686731cfb9cc103' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

the solution is using:
`<package id="MongoDB.Bson" version="2.4.4" targetFramework="net46" />`
any ideas?

**Comment by zell71** [comment]
ah the wiki is out of date.. the commits indicate sitecore is now using 8.2 v5.  the doc says to use an older version

**Comment by CAtSG** [comment]
Hi, I am running into the same issue.  Please could you let me what the fix was?  Thanks!

**Comment by zell71** [comment]
Hey - the sitecore version I was using wasn’t the version habitat was using.
I had an older version.
Make sure you are using the exact same version in the wiki notes. They’ve updated them now.
Another way to find the sitecore version is to look at the package.json in a project

**Comment by CAtSG** [comment]
Ah thanks.  I am new to both Sitecore 8 and habitat.  I am running Sitecore.NET 8.2 (rev. 161221) which is Update 2 and the wiki notes says Update 5.  So which version of habitat did you end up using?  I appreciate any insight.
