### ISSUE TITLE
V9 - Install SIF powershell error

### ISSUE THREAD

**Issue by fabiocarello** [Sitecore/Habitat#370]
Hello,
I'm installing the V9 version of Habitat trough the install-XP0 PS script on a Windows Server 2016 virtual machine. 

When it executes:

```
#Install SIF
$module = Get-Module -FullyQualifiedName @{ModuleName="SitecoreInstallFramework";ModuleVersion=$InstallerVersion}
if (-not $module) {
    write-host "Installing the Sitecore Install Framework, version $InstallerVersion" -ForegroundColor Green
   Install-Module SitecoreInstallFramework -RequiredVersion $InstallerVersion -Scope CurrentUser
   Import-Module SitecoreInstallFramework -RequiredVersion $InstallerVersion
}
```
I get the following error:
![image](https://user-images.githubusercontent.com/22072519/35575382-26b1b572-05d4-11e8-9b43-de9808fe9cd3.png)

In a previously non-habitat Sitecore XP 9.1 installation I had same issues with PS Repositories and sitecore.myget.org repo (both on Win Server 2012 and 2016) and I had to install SIF manaually.

I can't figure out how to solve this, and can't find online no one with this issue on Win 2016.
Any suggestion can help!

Thank you,

F.C.

**Comment by jeanfrancoislarente** [comment]
What is the output of Get-PSRepository ?

You should see 

![image](https://user-images.githubusercontent.com/5884676/35621000-e6d6a214-0650-11e8-8b13-1cb27fa547dc.png)

If you don't see that you need to Register-PSRepository
Is there an existing Repository with the same name pointing to a different source?

**Comment by fabiocarello** [comment]
Hello, 
it came out that for some reasone the repo source was wrong. (notice scpowershell intead of sc-powershell). 

Thanks for your help!
