### ISSUE TITLE
Another sync-Unicorn task error on "feature/V9" for Sitecore 9

### ISSUE THREAD

**Issue by henryhusunway** [Sitecore/Habitat#374]
### **Getting the following error with a fresh sitecore installation an most recent V9 code,   please shed some light for me,  thanks**
=============================

**# Method 'get_SegmentDefinitionIds' in type 'Sitecore.Marketing.Search.IndexedContactList' from assembly 'Sitecore.Marketing.Search, Version=11.15.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.**

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.TypeLoadException: Method 'get_SegmentDefinitionIds' in type 'Sitecore.Marketing.Search.IndexedContactList' from assembly 'Sitecore.Marketing.Search, Version=11.15.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

[TypeLoadException: Method 'get_SegmentDefinitionIds' in type 'Sitecore.Marketing.Search.IndexedContactList' from assembly 'Sitecore.Marketing.Search, Version=11.15.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.]
   System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type) +0
   System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName) +95
   System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark) +53
   System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase) +44
   Sitecore.DependencyInjection.<>c.<Configure>b__2_0(XmlNode x) +365
   System.Linq.WhereSelectEnumerableIterator`2.MoveNext() +223
   Sitecore.DependencyInjection.ServicesConfigurator.Configure(IServiceCollection serviceCollection) +366
   Sitecore.DependencyInjection.BaseServicesConfiguratorFactory.Configure(IServiceCollection serviceCollection) +159
   Sitecore.DependencyInjection.BaseServiceProviderBuilder.ConfigureServiceCollection() +142
   Sitecore.DependencyInjection.ServiceLocator.ConfigureServiceProvider() +240
   Sitecore.DependencyInjection.ServiceLocator.get_ServiceProvider() +514
   Sitecore.DependencyInjection.SitecorePerRequestScopeModule..ctor() +13

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck) +0
   System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark) +197
   System.Activator.CreateInstance(Type type, Boolean nonPublic) +105
   System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark) +1484
   System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes) +289
   System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture) +27
   System.Web.HttpRuntime.CreateNonPublicInstance(Type type, Object[] args) +79
   System.Web.HttpApplication.BuildIntegratedModuleCollection(List`1 moduleList) +222
   System.Web.HttpApplication.GetModuleCollection(IntPtr appContext) +1086
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +123
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +169
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +396
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +333

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +525
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +124
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +700

**Comment by rakeshbindal4** [comment]
download the sitecore 9 update 1 , copy the "Sitecore.Marketing.Search.dll" from this setup and paste it.

**Comment by JayFischer** [comment]
@rakeshbindal4 Awesome! This resolved my issue.

**Comment by faiyazulnoor** [comment]
https://github.com/Sitecore/Habitat/issues/363

**Comment by nickwesselman** [comment]
Need to confirm whether this is still an issue to be resolved on v9 branch.

**Comment by nickwesselman** [comment]
I'm unable to repro this, anyone else still seeing it?

**Comment by henryhusunway** [comment]
It is resolved now, thanks a lot 


    On Tuesday, June 26, 2018, 1:22:16 PM PDT, Nick Wesselman <notifications@github.com> wrote:  
 
 
I'm unable to repro this, anyone else still seeing it?

**Comment by nickwesselman** [comment]
Thank you @henryhusunway!
