### ISSUE TITLE
Error during installing Habit from Master branch for V8

### ISSUE THREAD

**Issue by yonka1** [Sitecore/Habitat#378]
Followed the instruction https://github.com/Sitecore/Habitat/wiki/01-Getting-Started, and get the following error: **Error: Requested URL: /unicorn.aspx cannot be found**.  Can anyone please help?

[11:01:47] Finished '04-Apply-Xml-Transform' after 4.18 s
[11:01:47] Starting '05-Sync-Unicorn'...
Error: Invoke-WebRequest :

Error:
        The resource cannot be found.

             Server Error in '/' Application.
             The resource cannot be found.

             Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been
removed, had its name changed, or is temporarily unavailable. &nbsp;Please review the following URL and make sure that
it is spelled correctly.

Error:              Requested URL: /unicorn.aspx

Error:

Error:             Version Information:&nbsp;Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.2623.0

Error:

Error:

Error: At C:\Sitecore\Habitat8\scripts\Unicorn\Unicorn.psm1:82 char:12

Error: + ...   $result = Invoke-WebRequest -Uri $url -TimeoutSec 360 -UseBasicPars ...

Error: +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error:     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc

Error:    eption

Error:     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

c:\Sitecore\Habitat8\scripts\unicorn.js:44
    if (err !== null) throw err;
                      ^

Error: Command failed: powershell -executionpolicy unrestricted "c:\Sitecore\Habitat8\scripts/Unicorn/./Sync.ps1 -secret 749CABBC85EAD20CE55E2C6066F1BE375D2115696C8A8B24DB6ED1FD60613086 -url http://habitat.dev.local/unicorn.aspx"
Invoke-WebRequest :

        The resource cannot be found.

            Server Error in '/' Application.
             The resource cannot be found.

             Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been
removed, had its name changed, or is temporarily unavailable. &nbsp;Please review the following URL and make sure that
it is spelled correctly.

             Requested URL: /unicorn.aspx

            Version Information:&nbsp;Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.2623.0

At C:\Sitecore\Habitat8\scripts\Unicorn\Unicorn.psm1:82 char:12
+ ...   $result = Invoke-WebRequest -Uri $url -TimeoutSec 360 -UseBasicPars ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)

**Comment by rk92269** [comment]
**Sitecore Habitat Hanging on 05-Sync-Unicorn**
Make sure to unblock following files in the code repository, you can do so by right click on each one of them and click on "Unblock":
Habitat-master\scripts\Unicorn\MicroCHAP.dll
Habitat-master\scripts\Unicorn\Sync.ps1
Habitat-master\scripts\Unicorn\Unicorn.psm1

**Comment by nickwesselman** [comment]
@yonka1 Were you able to resolve this issue? If you are still having trouble, please use [Sitecore Stackexchange](https://sitecore.stackexchange.com) or #helix-habitat on [Sitecore Community Slack](https://www.akshaysura.com/2015/10/27/how-to-join-sitecore-slack-community-chat/). This repository's issues are reserved for feature requests and bug reports. Thank you!

**Comment by ShravanKalva** [comment]
Started a fresh install on sitecore 9 update 2, same issue. Cant get through unicorn step, all the forums related to 8.2 habitat install.

**Comment by jeanfrancoislarente** [comment]
@ShravanKalva you should start a new thread/issue if you're on v9 as this issue is older and the solution may end up being related to v9 only.

Be sure to post details (error, etc) as well.

**Comment by nickwesselman** [comment]
@ShravanKalva and unless you believe it's a confirmed bug, please use Stackexchange or Sitecore Community Slack for troubleshooting assistance. This repository's issues are reserved for feature requests and bug reports. Thank you!
