### ISSUE TITLE
How to publish only specified solution

### ISSUE THREAD

**Issue by hrishikeshtt** [Sitecore/Habitat#381]
I want to publish only the specified projects to be published while running "Publish-Feature-Projects" gulp task. For this purpose I created a new solution and added only those projects to publish. How can I achieve this using gulp. Is there any way to read the solution file and get project location and publish only them ?

**Comment by nickwesselman** [comment]
You can publish individual modules using `Publish-Project`, e.g.
```
gulp Publish-Project -m Feature/Accounts
```

I suppose if you wanted to do more than one, you could create a PowerShell script or just do multiple gulp calls in the same command line with `;`.

In the future, please post usage questions in Community Slack or Sitecore Stackexchange. GitHub issues should be used for feature requests and bug reports. Thanks!
