### ISSUE TITLE
Suggestion: Foundation.SitecoreExtensions as a NuGet package

### ISSUE THREAD

**Issue by JamesSkemp** [Sitecore/Habitat#384]
Has any thought been given to pulling the Foundation.SitecoreExtensions module out of Habitat and making it a NuGet package, possibly on the Sitecore NuGet instance? It seems the 'community-driven' helper methods in Foundation.SitecoreExtensions would greatly benefit being pulled out of Habitat and escalated up a bit.

Years ago we ended up taking chunks of the old Sitecore.Sharedsource functionality and putting it onto our local NuGet instance, which helped considerably with our development.

We've pulled over much of these into our solutions, but given the namespace, have tried to stay away from modifying them (such as cleaning up unnecessary `using` statements and other items TeamCity likes to complain about) given the `Sitecore.x` namespace.

**Comment by nickwesselman** [comment]
Thanks for the suggestion @JamesSkemp. However that would both imply support of this code, which Sitecore is not providing at this time. My goal is to reduce the amount of code required in `SitecoreExtensions` by introducing more Helix principles into the core product.

**Comment by JamesSkemp** [comment]
Unfortunate to hear, but thanks @nickwesselman. I wondered if that might be the case, but since this repo is contained within the https://github.com/Sitecore account I assumed there was some oversight.

**Comment by nickwesselman** [comment]
There's definitely oversight, and we are continuing to invest in Habitat, but Product Support / Helpdesk does not support the Habitat repository.
