### ISSUE TITLE
Error executing install-xp0.ps1 - Principal IIS AppPool\DefaultAppPool was not found.

### ISSUE THREAD

**Issue by derekcorreia** [Sitecore/Habitat#390]
When executing the PS1 installer, I get the following error: 
```
Get-LocalGroupMember : Principal IIS AppPool\DefaultAppPool was not found.
At C:\projects\Habitat\install-xp0.ps1:87 char:11
+     if (!(Get-LocalGroupMember "Performance Log Users" "IIS AppPool\D ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (IIS AppPool\DefaultAppPool:String) [Get-LocalGroupMember], PrincipalNot
   FoundException
    + FullyQualifiedErrorId : PrincipalNotFound,Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand
```

PS Version 5.1.15063.502
Windows 10
SIF 1.2.1

**Comment by jeanfrancoislarente** [comment]
Script needs to change to remove "Default AppPool" user since the AppPool that is created by SIF is "IIS AppPool\<site-name>" ie: "IIS AppPool\habitat.dev.local"

**Comment by derekcorreia** [comment]
Nice catch @jeanfrancoislarente , thank you!

@nickwesselman , I can handle this change in the branch I'm working now, if you want to add this to the project. Thanks!

**Comment by nickwesselman** [comment]
Doh, thought I had fixed this in my commit yesterday but apparently not. If that change works, yeah go ahead and fix. Please reference issue # in commit. Thanks!

**Comment by nickwesselman** [comment]
Does this actually need to look at `$SitecoreSiteName` then? Might not be `habitat.dev.local`.

**Comment by derekcorreia** [comment]
That was how I was planning on fixing it, and moving it to the end of the ps script post-installation. Testing now...

**Comment by jeanfrancoislarente** [comment]
Agreed - habitat.dev.local was the example I provided. It's whatever the site name is going to be.
