### ISSUE TITLE
Ensure v9 branch compatibility with Sitecore.Demo.Group

### ISSUE THREAD

**Issue by derekcorreia** [Sitecore/Habitat#401]
Sitecore.Demo.Group solution is used in Helix workshops. Ensure prior to release the version of Habitat works with that solution, and change the Demo.Group solution as needed

**Comment by nickwesselman** [comment]
FYI @derekcorreia, things should be stable enough at this point to confirm this.

**Comment by derekcorreia** [comment]
@nickwesselman Thanks for the heads up -- will plan on pulling tomorrow, revving the Sitecore.Demo.Group solution to 9.0.2, then testing.

**Comment by derekcorreia** [comment]
Currently blocked by #422, but can get past that by building initially in VS. Having an issue in the demo project, and have to put it down for the day. Will pick back up monday, I think we can hope to call it good then.

**Comment by derekcorreia** [comment]
@nickwesselman As it sits right now, v9 branch is compatible with the Demo project. I will merge that feature branch to main when the habitat release gets merged up. 

Thank you again!
