### ISSUE TITLE
Update to Sitecore XP 9.0 Update-2

### ISSUE THREAD

**Issue by nickwesselman** [Sitecore/Habitat#403]
Now available:
https://dev.sitecore.net/Downloads/Sitecore_Experience_Platform/90/Sitecore_Experience_Platform_90_Update2.aspx

**Comment by DipakSinghYadav** [comment]
Xeeeedxdlf

Get xxdroid e
ecxeee xrc g xcfcrff
Cxee

From: Nick cxeexxm
M
Senrct: Thursday, 21 June, 6:59 PM
Subject: [Sitecore/Habitat] Update to Sitecore XP 9.0 Update-2 (#403eeXxeexcerxeeeeere
To: Si xx cx etecore/Habitat
Cc: SubHabitatxc xee xx eewxeex
Now a dcer available:
httpsxee exee xdreexxdzeew://dev.sitecore.net/Downloads/Sitecxxee a Dr reyeed crore_Experience_Platform/90/Sitec xxore_E xxxperience_Platform_90_Update2.asefercx<https://dev.sitecore.net/Downloads/Sitecore_Experience_Platform/90/Sitecore_Experience_Platform_90_Update2.aspx>,spx
