### ISSUE TITLE
v9 branch won't build because of Sitecore reference errors

### ISSUE THREAD

**Issue by scott-stoltz** [Sitecore/Habitat#404]
Hello. I pulled down the latest v9 branch and when I open in the latest VS 2017, I see squiggly lines all over the place and build errors when trying to build. 

Mostly all reference errors, like "The type or namespace name 'Mvc' does not exist in the namespace 'Sitecore'" and "'HtmlHelper<Mvc.Presentation.RenderingModel>' does not contain a definition for 'Sitecore' and no extension method 'Sitecore' accepting a first argument of type 'HtmlHelper<Mvc.Presentation.RenderingModel>' could be found"

Obviously something messed up with the Sitecore references, but I've restored Nuget packages and checked the references and everything looks correct.

Thoughts?

**Comment by nickwesselman** [comment]
Hi @scott-stoltz -- Thanks for reporting, but I'm unable to reproduce. Are you sure the nuget packages restored successfully? Is the Habitat `nuget.config` with the Sitecore nuget feeds not applying for some reason?

Can you check the project references? Are there specific assemblies which are erroring? Thanks!

**Comment by nickwesselman** [comment]
Thanks @scott-stoltz. Habitat doesn't use the newer `PackageReference` approach, and the solution isn't set up for automatic package restore. The expectation is that you'd be using the gulp tasks, which include a `Nuget-Restore` task.

I'll log a backlog item to look at whether Habitat can use `PackageReference` or not, will depend on whether any required packages are dependent on `install.ps1` scripts, xdt transforms, etc.
