### ISSUE TITLE
Getting Started Updates

### ISSUE THREAD

**Issue by nickwesselman** [Sitecore/Habitat#427]
- [x] copying Sitecore libs no longer needed w/ use of nuget
- [x] copying license.xml for FakeDb shouldn't be needed either, can use from `build` folder
- [x] update docs on default Gulp tasks
- [x] ensure Getting Started docs have correct Sitecore version, etc

**Comment by jeanfrancoislarente** [comment]
Keep in mind that SXA (and other optional modules) are not available on NuGet. Having references to SXA components in your project would still require the CopyLibs functionality for a proper build.

**Comment by nickwesselman** [comment]
@jeanfrancoislarente No other modules needed at the moment, can always bring it back if it's needed. Or hopefully we can just solve those missing nuget packages.
