### ISSUE TITLE
xconnect-XP0.json contains solr version as 6.6.1

### ISSUE THREAD

**Issue by onpoc** [Sitecore/Habitat#447]
Is it correct that xconnect-XP0.json contains "DefaultValue": "c:\\solr-6.6.1"?
Because here we are using solr-6.6.2 with habitat

**Comment by jeanfrancoislarente** [comment]
Despite the bug in 6.6.1 prior versions of Sitecore shipped with that version as having been tested. It wouldn't hurt to update the default but isn't a "mistake" or anything.
