### ISSUE TITLE
Let Habitat be a starter kit

### ISSUE THREAD

**Issue by GoranHalvarsson** [Sitecore/Habitat#459]
So there has been a lot of "Habitat is not a starter kit". I have to a disagree, I think Habitat should be THE starter kit.  In order to make it happen, we probably need to do some changes. Perhaps we could have like a baseline or something. With just a few "vital" projects, like dictionary, theming, assets and so on. What do you think?

**Comment by dnstommy** [comment]
I think that has to be maintained under something like https://github.com/muso31/Helixbase. I don't think Habitat and demos like Home should be considered base kits.

**Comment by dnstommy** [comment]
I think storefront is accepted as "do as I do" because there is so little code for Sitecore Commerce. We have tons of code for Sitecore CMS. The issue with bootstrap is that every boot strap site looks like a bootstrap site. We don't want 100 Habitat sites in the world. All with the same structure and issues. 

People need to understand how Sitecore is designed by building from scratch and discovering why best practice exist. SXA exists and that is an acceptable "base" project that Sitecore supports. But for Vanilla, we need to develop it. If you want to take Foundation projects, I support that. But features need to be self developed. There are many things about Habitat that I don't like. And since I don't use it, I get to do what I think is best.

Friends don't let friends use Habitat as a starter project.

**Comment by derekcorreia** [comment]
The predicament is that Habitat wasn't designed as a way of getting you started with bootstrapping ( metaphorically, not technically :) ) Sitecore development. While I wasn't involved in its inception, Sitecore's been pretty clear that the goals for Habitat were:

- To show developers new to the platform a working example that could be inspected and learned from (How views get referenced in rendering definition items, how content can be serialized, where it goes and how it works). If I think back to when I learned Sitecore initially, I would have loved to have an example with code and items to peek and poke at to see how it's all wired together. Habitat's pretty good for that.
- To all developers, show how a site that followed Helix principles _could_ be architected. If read alongside the helix docs, it can show good concepts of modules, layers, and other core concepts.

There were other periphery goals too (showing how some tooling like Gulp _could_ be used, demonstrating Unicorn, etc), but those are the main two. It's hard to be an example for an architecture and a learning tool **and** a starter kit.

If you look through many of the discussions here, there's lots of issues on why _____ in Habitat is wrong/inefficient/should be implemented differently -- __and that's a good thing!!__. A solution is requirements + technology, and most requirements may put you squarely at odds from how different requirements get implemented in another solution. Neither of those makes one wrong, just informed differently by the needs of your specific implementation, and there are more often more than one way to follow a principle.

There are plenty of great community solutions and tooling that strive to accelerate or kickstart a Helix implementation -- and that's great (Chris noted a great one above). We've also very much heard the need for more examples, definitions, and tooling -- @nickwesselman is leading the charge in Sitecore moving forward on improving things from those areas. But the goals of Habitat are too far removed from being a starter kit without impacting what it needs to be -- an architecture and working example of Helix. I'm not being dismissive of the need, just that this isn't the right solution to fill it.

**Comment by GoranHalvarsson** [comment]
I agree totally that current "version" of Habitat should NOT be a starter kit. But from that we could do a baseline that is accepted as a starter kit. I mean perhaps a totally new repository, Sitecore Starterkit where we/sitecore will create an ACCEPTED baseline for a starter kit.  Again no community starter kit a Sitecore starter kit. What say you :)

**Comment by GoranHalvarsson** [comment]
@jeanfrancoislarente Ah yes exactly, I missed that. Ok then I'm happy :)

**Comment by nickwesselman** [comment]
As others have mentioned, my goal going forward is definitely to:

* Decrease the need for oft-copied Foundation projects by incorporating must-needed features into core product
* Provide developer tooling for spinning up / bootstrapping new Sitecore solutions / projects from a provided template

Definitely see the need for these, but Habitat will not be the vehicle for them. :)
