### ISSUE TITLE
I do not find prerequisites.json in build/assets folder

### ISSUE THREAD

**Issue by mahesh-bhide** [Sitecore/Habitat#460]
Note: for support questions, please use [Sitecore Stackexchange](https://sitecore.stackexchange.com) or #helix-habitat on [Sitecore Community Slack](https://www.akshaysura.com/2015/10/27/how-to-join-sitecore-slack-community-chat/). This repository's issues are reserved for feature requests and bug reports.

**Describe the bug**

**Sitecore Version**
The specific version and revision of Sitecore you have installed.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mahesh-bhide** [comment]
Settings.ps1 file expects prerequisites.json folder in build/assets folder. I dont see that file in build/assets.

**Comment by jeanfrancoislarente** [comment]
Prerequisites.json file comes with the Sitecore 9.1 OnPrem download, nested in the Configuration zip file.
ie: Sitecore 9.1.0 rev. 001564 (WDP XP0 packages).zip
