### ISSUE TITLE
Sitecore after Habitat setup admin login redirect to HTTP Error 404.0 - Not Found

### ISSUE THREAD

**Issue by phamtheanhphu** [Sitecore/Habitat#473]
Hi,

I have used Sitecore 9.1.0 and setup Habitat on it, I have built, deployed and synced unicorn successfully.

The front-page displays okie but when I tried to login to admin page (http://habitat.dev.local/sitecore - redirect to: http://habitat.dev.local/identity/login/shell/SitecoreIdentityServer) it showed the  "HTTP Error 404.0 - Not Found" default IIS page.

Please help me with this issue.

Thank & have a nice day.

**Comment by VadzimPapko** [comment]
Hello @phamtheanhphu,

to get a help response more faster you need to forward your question to [Sitecore StackExchange ](https://sitecore.stackexchange.com). 

and firstly, do not forget to find out the same question has been already added.
https://sitecore.stackexchange.com/questions/tagged/habitat

**Comment by nickwesselman** [comment]
Hi @phamtheanhphu -- yes as mentioned, Stackexchange or #helix-habitat on the Community Slack is better for troubleshooting. We like to keep GitHub limited to bug reports and feature requests.

That said it seems perhaps your Identity Server may not have installed properly. I'd try installing Sitecore again and ensure the SIF install completes without error.
