### ISSUE TITLE
Field Editor &shy; in Single line Text fields are dissapearing on save

### ISSUE THREAD

**Issue by squadwuschel** [Sitecore/Habitat#478]
**Describe the bug**
When I use the Field Editor for single line Text fields and when I edit this fields and when I am using shy inside my name like

      &shy; => in the text below only "shy"

![grafik](https://user-images.githubusercontent.com/1572878/62866646-a4e3d880-bd11-11e9-87bc-20c0ad846c5d.png)

The fields in the page are not getting updated, mostly I need to save the hole page. but after saving the page  - the shy is gone not shown on the page

![grafik](https://user-images.githubusercontent.com/1572878/62866738-e3799300-bd11-11e9-8462-08934e47048f.png)

when I then save the page the shy is gone and overwritten.

![grafik](https://user-images.githubusercontent.com/1572878/62866814-191e7c00-bd12-11e9-96f6-521eb4438be4.png)

as you can see on the side its not rendered any more.

**A clear and concise description of what the bug is.**
When you add e.g. shy to a single line Text field and you edit this field with the Field Editor and after accepting the change and saving the page the &shy; is gone.

**Sitecore Version**
9.0 Update 2

**To Reproduce**

- Use the field Editor button on template with a single line text field
- Insert some text line to the Text
  
        "Informatio&shy;en" 

- Accept the Field Editor changes
- The modal closes but is not showing the changes directly
- Save the page
- go to your edited field there is no shy use the Field Editor button => and you see no shy

**Expected behavior**
- When you edit some code in the field editor and accept the changes with "OK" the changes should be updated to the page inputs directly
- when you use shy in the field editor it sould not be deleted after "ok" and saving the page.
(when you directly edit the text inside the experience editor and add the shy inside the field it is not disappearing)

**Additional context**
I am not shure if this is a bug from sitecore itself or a problem with the code from Habitat. If this is a sitecore problem. How can I address it without getting told from sitecore that they are not supporting habitat issues?

**Comment by nickwesselman** [comment]
Hi @squadwuschel,

Offhand this does not look like an issue with Habitat. AFAIK you've always had to do a "save" after editing something with a Field Editor, though I agree having an auto-save would be better behavior by the EE.  Single-line text fields don't support HTML / HTML entities either AFAIK, have you tried putting the character directly in the field? It should be encoded on output.

You could test these behaviors pretty easily on a vanilla/empty instance by adding a Field Editor to the out-of-the-box sample renderings. If you see something different than Habitat, I'd be very surprised but interested in knowing. If, as I suspect, you see the same behavior, you can use that as your source for your support ticket.

Please reopen if needed.

-Nick
