### ISSUE TITLE
Update Old Dates in content data

### ISSUE THREAD

**Issue by VadzimPapko** [Sitecore/Habitat#481]
Currently the Habitat site contains a bit old data such as
![image](https://user-images.githubusercontent.com/3023032/65044430-8baff680-d965-11e9-8837-15fb3129cff6.png)

Sometimes it needs to present this demo site to potential clients and they a bit scared when seeing old dates.

I think we can improve this - make a date generation dynamically as an example.

**Comment by VadzimPapko** [comment]
@nickwesselman could please review this issue? thank you in advance!

**Comment by nickwesselman** [comment]
@VadzimPapko Sorry, this is a "won't fix." Habitat is not intended as a demo platform any more, please see Habitat Home. We are also in process of replacing Habitat with a new set of developer Helix Examples.

**Comment by VadzimPapko** [comment]
@nickwesselman got it! Thank you for explanation!
