### ISSUE TITLE
web.config

### ISSUE THREAD

**Issue by huzzi** [Sitecore/Habitat#52]
Could you please tell what I'm doing wrong when I run 02-Publish-All-Projects the web.config file is getting overridden with the content below?

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
      <remove name="OPTIONSVerbHandler" />
      <remove name="TRACEVerbHandler" />
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
    </handlers>
  </system.webServer>
  <system.codedom>
    <compilers>
      <compiler language="c#;cs;csharp" extension=".cs"
        type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
        warningLevel="4" compilerOptions="/langversion:6 /nowarn:1659;1699;1701"/>
      <compiler language="vb;vbs;visualbasic;vbscript" extension=".vb"
        type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.VBCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
        warningLevel="4" compilerOptions="/langversion:14 /nowarn:41008 /define:_MYTYPE=\&quot;Web\&quot; /optionInfer+"/>
    </compilers>
  </system.codedom>
</configuration>

I've replaced the web.config from a clean install but running unicorn to sync Habitat.Framework.Assets I get 

ERROR: Exception of type 'Sitecore.Data.Serialization.Exceptions.ParentItemNotFoundException' was thrown. (Sitecore.Data.Serialization.Exceptions.ParentItemNotFoundException)

What am I doing wrong? Thanks again for this brilliant framework.

**Comment by dashkodo** [comment]
02-Publish-All-Projects should not override web.config. Looks like issue

**Comment by huzzi** [comment]
I'll try again with clean install see what happens.

**Comment by alinulms** [comment]
Have you created a project and forgot to remove the web.config file from it?

**Comment by huzzi** [comment]
Everything is fine with a clean install. Thanks.
