### ISSUE TITLE
Multiple predicate include nodes had the same name 

### ISSUE THREAD

**Issue by bennich** [Sitecore/Habitat#60]
Hi Guys

When updating my Habitat to the latest version, I get the above error from Unicorn.
![2015-12-15_09-17-30](https://cloud.githubusercontent.com/assets/1506842/11805530/b62fafc4-a30c-11e5-8ed9-45ab56a6eebf.png)

Have looked through all config files, and are unable to find any double entries. 
Have found a single <include> element that is not named in the Habitat.Framework.Serialization.config file, however giving it a name doesn't change anything.

Have tried to get a set of Habitat config files from a previous working copy of habitat, that didn't change anything either.

Have cleared out and deleted all temporary asp.net files as well.

Do you have any ideas as to what might cause this?

**Comment by stasmaxymov** [comment]
Hi,

We have recently finished massive renaming/restructuring in Habitat and configs were moved to another folders. One that contain Habitat.Website.Templates section is under "App_Config\Include\Project" folder.

I suggest you to reinstall Habitat on clean Sitecore

**Comment by bennich** [comment]
I will reinstall - thx.
