### ISSUE TITLE
Unicorn error - Foundation.Multisite and Feature.Multisite

### ISSUE THREAD

**Issue by GoranHalvarsson** [Sitecore/Habitat#63]
I get following error in the "Unicorn Configurations page" for MultiSite(both Foundation and Feature)

This configuration's predicate cannot resolve any valid root items. This usually means it is configured to look for nonexistent paths or GUIDs. Please review your predicate configuration.

![foundationmultisite](https://cloud.githubusercontent.com/assets/726479/11932909/eb9b7ff8-a7f8-11e5-91d1-a2fb296e61ab.PNG)

![featuremultisite](https://cloud.githubusercontent.com/assets/726479/11932913/f1191eb8-a7f8-11e5-8a59-9a557cc00ca6.PNG)

Any ideas?

**Comment by mhwelander** [comment]
+1 I got that as well - after the publish profiles were updated (but I don't know if that's related). I published the projects individually to get around it, and that seemed to work.

**Comment by stasmaxymov** [comment]
The error you saw is expected for new modules, which haven't been synced yet. Just run sync for Foundation.Multisite and then for Feature.Multisite

**Comment by mhwelander** [comment]
@stasmaxymov By sync, do you mean re-publish the projects in Visual Studio or something else? If @GoranHalvarsson has the same problem as me, there are no sync buttons in the UI - just the red error.

**Comment by GoranHalvarsson** [comment]
Thanks @mhwelander. 
I had to manually create folders(in Sitecore):
/sitecore/templates/Foundation/Multisite
/sitecore/templates/Feature/Multisite
/sitecore/layout/Renderings/Feature/Multisite

And now Unicorn is well again :-)

**Comment by GoranHalvarsson** [comment]
By the way, in "Foundation.Multisite.Serialization.config" I noticed:
```
<include name="Feature.Multisite.Templates" database="master"
                     path="/sitecore/templates/Foundation/Multisite" />
```
Should it not be:
```
<include name="Foundation.Multisite.Templates" database="master"
                     path="/sitecore/templates/Foundation/Multisite" /> 
```
