### ISSUE TITLE
MVC with RazorGenerator & Precompiled View Engine

### ISSUE THREAD

**Issue by JBaltika** [Sitecore/Habitat#77]
Hi guys,
Quick question. I just was looking in project and have one question. Why not use RazorGenerator & Precompiled View Engine? It would make webapp load faster, better for deployments as its DLL required to deploy or revert in case problems. Less chance to make an error and many other perks coming static vs runtime compilation. I am pretty sure it's a way to do that in Sitecore MVC. The teams just do great job to separating to the projects any way right now.  Add razorgenerator.directives file at root of MVC project with directives:
GeneratePrettyNames: true

 And later add custom tool name for each *.cshtml file. This is a not  huge effort .

http://blog.davidebbo.com/2011/06/precompile-your-mvc-views-using.html

http://www.c-sharpcorner.com/UploadFile/97fc7a/article-precompiled-razor-view-using-razorgenerator-mvc-and/

Imagine a huge sitecore implementation with hundreds of *.cshtml files for many sites & development & maintenance issues, this is just  a thought....
J.B

**Comment by kamsar** [comment]
:+1: I use this in my solutions, as do several other folks I've heard of. Easy install, mildly slower compiles, but compile-time checking of view syntax and faster solution startup time.

Now if only Sitecore shipped with the precompiled view engine and had all those darn SPEAK views compiled into an assembly ;)

http://kamsar.net/index.php/2016/01/Benchmark-Show-Precompilation/

**Comment by Eldblom** [comment]
Generally a good idea. Seeing that Habitat acts as an educational example, I think that the concept might be a bit alien for many devs - and such will confuse more than it will benefit.
Great stuff for a blog post though:)
