### ISSUE TITLE
Adding a new website

### ISSUE THREAD

**Issue by AlexPerotti** [Sitecore/Habitat#82]
Most likely it isn't an issue, but I'm struggling to add a new website under the habitat structure. I've created a new project (under projects), created configuration and so but it seems that I make a mistake in the site configuration since I can't access the site through the url (I've configured hosts file and IIS)

Here is the config file

```xml
<?xml version="1.0"?>

<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/">
  <sitecore>
    <events>
      <event name="publish:end">
        <handler type="Sitecore.Publishing.HtmlCacheClearer, Sitecore.Kernel" method="ClearCache">
          <sites hint="list">
            <site hint="mscpoc">mscpoc</site>
          </sites>
        </handler>
      </event>
      <event name="publish:end:remote">
        <handler type="Sitecore.Publishing.HtmlCacheClearer, Sitecore.Kernel" method="ClearCache">
          <sites hint="list">
            <site hint="mscpoc">mscpoc</site>
          </sites>
        </handler>
      </event>
    </events>
    <sites>
      <site name="mscpoc" patch:before="site[@name='modules_website']" hostname="mscpoc" database="web" virtualfolder="/" physicalfolder="/" rootpath="/sitecore/content/mscpoc" startitem="/Home" dictionarypath="/sitecore/content/mscpoc/global/dictionary" domain="extranet" allowdebug="true" cachehtml="true" htmlcachesize="50mb" registrycachesize="0" viewstatecachesize="0" xslcachesize="25mb" filtereditemscachesize="10mb" enablepreview="true" enablewebedit="true" enabledebugger="true" disableclientdata="false" cacherenderingparameters="true" renderingparameterscachesize="10mb" formsroot="{f1f7aab6-c8ce-422f-a214-f610c109fa63}" />
    </sites>
    <cacheSizes>
      <sites>
        <mscpoc>
          <html>50MB</html>
          <registry>0</registry>
          <viewState>0</viewState>
          <xsl>25MB</xsl>
        </mscpoc>
      </sites>
    </cacheSizes>
    <settings>
      <setting name="Preview.DefaultSite" value="mscpoc" />
    </settings>
  </sitecore>
</configuration>
```

**Comment by brucedg** [comment]
Hi Alex, I have just done a multisite set up and a few notes: 
Sitecore 8 has separated the multi-site config out into individual site config files (habitat.local\Website\App_Config\Include\Project - i.e. habitat.config) So I created config files for each site.

The sites node look likes this: Please note the hostName (case sensitive) attribute which made things work for me. 

<sites>
      <site name="Workscheme" hostName="workscheme" patch:before="site[@name='scheduler']" database="master" virtualFolder="/" physicalFolder="/" rootPath="/sitecore/content/Workscheme" startItem="/Home/For Employers" dictionaryPath="/sitecore/content/southern cross/global/dictionary" domain="extranet" allowDebug="true" cacheHtml="true" htmlCacheSize="50MB" registryCacheSize="0" viewStateCacheSize="0" xslCacheSize="25MB" filteredItemsCacheSize="10MB" enablePreview="true" enableWebEdit="true" enableDebugger="true" disableClientData="false" cacheRenderingParameters="true" renderingParametersCacheSize="10MB" formsRoot="{F1F7AAB6-C8CE-422F-A214-F610C109FA63}" />
    </sites>

Hope this helps

**Comment by brucedg** [comment]
<sites>
      <site name="Workscheme" hostName="workscheme" patch:before="site[@name='scheduler']"

**Comment by AlexPerotti** [comment]
Hi Bruce,

thank you for your answer.

I've done pretty much the same, but for some reason it didn't worked. Now I regenarate my config file from scratch, compying from the one in the demo project, and is working.
