### ISSUE TITLE
Wrong namespace in Foundation.Indexing 

### ISSUE THREAD

**Issue by JobiJoba** [Sitecore/Habitat#86]
Hi guys, 

The ISearchServiceRepository in https://github.com/Sitecore/Habitat/blob/master/src/Foundation/Indexing/code/Repositories/ISearchServiceRepository.cs & ISearchSettingsRepository

have the namespace : namespace Sitecore.Feature.News.Repositories

**Comment by dashkodo** [comment]
Fixed
