### ISSUE TITLE
Accounts Feature, some stuff to extract to Foundation

### ISSUE THREAD

**Issue by JobiJoba** [Sitecore/Habitat#87]
Hi, 

What do you think about extracting some of the code of the Accounts Feature like  : 

- ContactProfileService
- AccounTrackerService
- UserProfileService 
- UserProfileProvider

To a new project in Foundation which will take care of all the aspect about "The user" , "The contact", etc 

I wanted to use some of these methods during the hackathon, but i wouldn't have reference to a feature project.

**Comment by Eldblom** [comment]
Sound like a really good idea. If e.g, you are incorporating commerce in the solution you might want to have a Customer feature module - which will probably require the ContactProfileService and UserProfileService.
