### ISSUE TITLE
Pipelines LinkProvider

### ISSUE THREAD

**Issue by JobiJoba** [Sitecore/Habitat#88]
Hey, 

It would be nice to create a Pipelines Link Provider";
As projects are decomposed in Feature, it would be a great idea if for each project we can (if necessary) just add a pipelines instead of patching the LinkManager. 

Here is a blog post explaining the things : http://thegrumpycoder.com/post/78684655662/sitecore-pipeline-enabled-linkprovider 

What do you think ?

**Comment by JobiJoba** [comment]
Mmmm maybe it's not necessary ... should a feature manage the url ? it's probably something which should manage the Project part ?

**Comment by Eldblom** [comment]
I agree that it's in a gray zone. A single feature might need to manage parts of the URL, e.g. products in a catalogue or news in a bucket. On the other hand, the URL is typically website specific (not feature specific), which means that multiple websites might have different URL preferences for the same feature.
Maybe cross that bridge when a feature module requires it?
