### ISSUE TITLE
Adding changes in webconfig(In a foundation project)

### ISSUE THREAD

**Issue by GoranHalvarsson** [Sitecore/Habitat#90]
Hello
If I need to add stuff to the webconfig, in this case it's a Foundation project. How do I do that? Do I add webtransform in that specific project, or ? Help me Obi Wan Kenobi you're my only hope :-)

**Comment by dashkodo** [comment]
You need add *.transform file to your project and modify gulp task _"03-Apply-Xml-Transform"_ to watch foundation layer too

**Comment by GoranHalvarsson** [comment]
Great mr, thanks :-)
